/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SignupAgentRouteImport } from './routes/signup_.agent'
import { Route as MyagentAgentSlugRouteImport } from './routes/myagent.$agentSlug'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminMigrationRouteImport } from './routes/admin.migration'
import { Route as AdminImportRequestsRouteImport } from './routes/admin.import-requests'
import { Route as AdminHierarchyRouteImport } from './routes/admin.hierarchy'
import { Route as AdminCsvImportRouteImport } from './routes/admin.csv-import'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCarriersRouteImport } from './routes/admin.carriers'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedPostDealRouteImport } from './routes/_authenticated/post-deal'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPhoneRouteImport } from './routes/_authenticated/phone'
import { Route as AuthenticatedNovaRouteImport } from './routes/_authenticated/nova'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNewsFeedRouteImport } from './routes/_authenticated/news-feed'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractingRouteImport } from './routes/_authenticated/contracting'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedCarrierSyncRouteImport } from './routes/_authenticated/carrier-sync'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBookOfBusinessRouteImport } from './routes/_authenticated/book-of-business'
import { Route as AuthenticatedBackOfficeRouteImport } from './routes/_authenticated/back-office'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedContractingIndexRouteImport } from './routes/_authenticated/contracting/index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiPublicWaitlistSignupRouteImport } from './routes/api/public/waitlist-signup'
import { Route as ApiPublicWaitlistCountRouteImport } from './routes/api/public/waitlist-count'
import { Route as ApiPublicPageDataRouteImport } from './routes/api/public/page-data'
import { Route as ApiPublicLeadSubmitRouteImport } from './routes/api/public/lead-submit'
import { Route as ApiPublicLandingLeadRouteImport } from './routes/api/public/landing-lead'
import { Route as ApiPublicFunnelViewRouteImport } from './routes/api/public/funnel-view'
import { Route as ApiPublicFunnelApplyRouteImport } from './routes/api/public/funnel-apply'
import { Route as AgentAgentSlugTemplateSlugRouteImport } from './routes/agent.$agentSlug.$templateSlug'
import { Route as AuthenticatedToolsLeadsRouteImport } from './routes/_authenticated/tools/leads'
import { Route as AuthenticatedSettingsNovaProRouteImport } from './routes/_authenticated/settings.nova-pro'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings.billing'
import { Route as AuthenticatedResourcesStateLicensesRouteImport } from './routes/_authenticated/resources/state-licenses'
import { Route as AuthenticatedResourcesScriptsRouteImport } from './routes/_authenticated/resources/scripts'
import { Route as AuthenticatedResourcesNewAgentGuideRouteImport } from './routes/_authenticated/resources/new-agent-guide'
import { Route as AuthenticatedResourcesAgentHandbookRouteImport } from './routes/_authenticated/resources/agent-handbook'
import { Route as AuthenticatedResourcesAgentAcademyRouteImport } from './routes/_authenticated/resources/agent-academy'
import { Route as AuthenticatedNovaSettingsRouteImport } from './routes/_authenticated/nova/settings'
import { Route as AuthenticatedNovaActivityRouteImport } from './routes/_authenticated/nova/activity'
import { Route as AuthenticatedContractingTransfersRouteImport } from './routes/_authenticated/contracting/transfers'
import { Route as AuthenticatedContractingInviteRouteImport } from './routes/_authenticated/contracting/invite'
import { Route as AuthenticatedContractingCommissionGridsRouteImport } from './routes/_authenticated/contracting/commission-grids'
import { Route as AuthenticatedContractingCarriersRouteImport } from './routes/_authenticated/contracting/carriers'
import { Route as AuthenticatedContractingAnnuityTrainingRouteImport } from './routes/_authenticated/contracting/annuity-training'
import { Route as AuthenticatedBackOfficeRecruitingTrackerRouteImport } from './routes/_authenticated/back-office/recruiting-tracker'
import { Route as AuthenticatedBackOfficeRecruitingFunnelsRouteImport } from './routes/_authenticated/back-office/recruiting-funnels'
import { Route as AuthenticatedBackOfficeMarketingTrackerRouteImport } from './routes/_authenticated/back-office/marketing-tracker'
import { Route as AuthenticatedBackOfficeClientMarketingRouteImport } from './routes/_authenticated/back-office/client-marketing'
import { Route as AuthenticatedBackOfficeCaseDesignRouteImport } from './routes/_authenticated/back-office/case-design'
import { Route as AuthenticatedBackOfficeAdvancedDeskRouteImport } from './routes/_authenticated/back-office/advanced-desk'
import { Route as AuthenticatedAgencyTeamRouteImport } from './routes/_authenticated/agency.team'
import { Route as AuthenticatedAgencySettingsRouteImport } from './routes/_authenticated/agency/settings'
import { Route as AuthenticatedAccountProducerProfileRouteImport } from './routes/_authenticated/account/producer-profile'
import { Route as AuthenticatedAccountMyLandingPageRouteImport } from './routes/_authenticated/account/my-landing-page'
import { Route as AuthenticatedAccountHelpRouteImport } from './routes/_authenticated/account/help'
import { Route as AuthenticatedAccountFaqRouteImport } from './routes/_authenticated/account/faq'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksFetchNewsRouteImport } from './routes/api/public/hooks/fetch-news'
import { Route as AuthenticatedBackOfficeCaseDesignAdminRouteImport } from './routes/_authenticated/back-office/case-design.admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SignupAgentRoute = SignupAgentRouteImport.update({
  id: '/signup_/agent',
  path: '/signup/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const MyagentAgentSlugRoute = MyagentAgentSlugRouteImport.update({
  id: '/myagent/$agentSlug',
  path: '/myagent/$agentSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMigrationRoute = AdminMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRequestsRoute = AdminImportRequestsRouteImport.update({
  id: '/import-requests',
  path: '/import-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHierarchyRoute = AdminHierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCsvImportRoute = AdminCsvImportRouteImport.update({
  id: '/csv-import',
  path: '/csv-import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarriersRoute = AdminCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostDealRoute = AuthenticatedPostDealRouteImport.update({
  id: '/post-deal',
  path: '/post-deal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhoneRoute = AuthenticatedPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNovaRoute = AuthenticatedNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNewsFeedRoute = AuthenticatedNewsFeedRouteImport.update({
  id: '/news-feed',
  path: '/news-feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContractingRoute =
  AuthenticatedContractingRouteImport.update({
    id: '/contracting',
    path: '/contracting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCarrierSyncRoute =
  AuthenticatedCarrierSyncRouteImport.update({
    id: '/carrier-sync',
    path: '/carrier-sync',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookOfBusinessRoute =
  AuthenticatedBookOfBusinessRouteImport.update({
    id: '/book-of-business',
    path: '/book-of-business',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBackOfficeRoute = AuthenticatedBackOfficeRouteImport.update({
  id: '/back-office',
  path: '/back-office',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractingIndexRoute =
  AuthenticatedContractingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaitlistSignupRoute = ApiPublicWaitlistSignupRouteImport.update({
  id: '/api/public/waitlist-signup',
  path: '/api/public/waitlist-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaitlistCountRoute = ApiPublicWaitlistCountRouteImport.update({
  id: '/api/public/waitlist-count',
  path: '/api/public/waitlist-count',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPageDataRoute = ApiPublicPageDataRouteImport.update({
  id: '/api/public/page-data',
  path: '/api/public/page-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadSubmitRoute = ApiPublicLeadSubmitRouteImport.update({
  id: '/api/public/lead-submit',
  path: '/api/public/lead-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLandingLeadRoute = ApiPublicLandingLeadRouteImport.update({
  id: '/api/public/landing-lead',
  path: '/api/public/landing-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFunnelViewRoute = ApiPublicFunnelViewRouteImport.update({
  id: '/api/public/funnel-view',
  path: '/api/public/funnel-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFunnelApplyRoute = ApiPublicFunnelApplyRouteImport.update({
  id: '/api/public/funnel-apply',
  path: '/api/public/funnel-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAgentSlugTemplateSlugRoute =
  AgentAgentSlugTemplateSlugRouteImport.update({
    id: '/agent/$agentSlug/$templateSlug',
    path: '/agent/$agentSlug/$templateSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedToolsLeadsRoute = AuthenticatedToolsLeadsRouteImport.update({
  id: '/tools/leads',
  path: '/tools/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsNovaProRoute =
  AuthenticatedSettingsNovaProRouteImport.update({
    id: '/settings/nova-pro',
    path: '/settings/nova-pro',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResourcesStateLicensesRoute =
  AuthenticatedResourcesStateLicensesRouteImport.update({
    id: '/state-licenses',
    path: '/state-licenses',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesScriptsRoute =
  AuthenticatedResourcesScriptsRouteImport.update({
    id: '/scripts',
    path: '/scripts',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesNewAgentGuideRoute =
  AuthenticatedResourcesNewAgentGuideRouteImport.update({
    id: '/new-agent-guide',
    path: '/new-agent-guide',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesAgentHandbookRoute =
  AuthenticatedResourcesAgentHandbookRouteImport.update({
    id: '/agent-handbook',
    path: '/agent-handbook',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesAgentAcademyRoute =
  AuthenticatedResourcesAgentAcademyRouteImport.update({
    id: '/agent-academy',
    path: '/agent-academy',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedNovaSettingsRoute =
  AuthenticatedNovaSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedNovaRoute,
  } as any)
const AuthenticatedNovaActivityRoute =
  AuthenticatedNovaActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedNovaRoute,
  } as any)
const AuthenticatedContractingTransfersRoute =
  AuthenticatedContractingTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedContractingInviteRoute =
  AuthenticatedContractingInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedContractingCommissionGridsRoute =
  AuthenticatedContractingCommissionGridsRouteImport.update({
    id: '/commission-grids',
    path: '/commission-grids',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedContractingCarriersRoute =
  AuthenticatedContractingCarriersRouteImport.update({
    id: '/carriers',
    path: '/carriers',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedContractingAnnuityTrainingRoute =
  AuthenticatedContractingAnnuityTrainingRouteImport.update({
    id: '/annuity-training',
    path: '/annuity-training',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedBackOfficeRecruitingTrackerRoute =
  AuthenticatedBackOfficeRecruitingTrackerRouteImport.update({
    id: '/recruiting-tracker',
    path: '/recruiting-tracker',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)
const AuthenticatedBackOfficeRecruitingFunnelsRoute =
  AuthenticatedBackOfficeRecruitingFunnelsRouteImport.update({
    id: '/recruiting-funnels',
    path: '/recruiting-funnels',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)
const AuthenticatedBackOfficeMarketingTrackerRoute =
  AuthenticatedBackOfficeMarketingTrackerRouteImport.update({
    id: '/marketing-tracker',
    path: '/marketing-tracker',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)
const AuthenticatedBackOfficeClientMarketingRoute =
  AuthenticatedBackOfficeClientMarketingRouteImport.update({
    id: '/client-marketing',
    path: '/client-marketing',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)
const AuthenticatedBackOfficeCaseDesignRoute =
  AuthenticatedBackOfficeCaseDesignRouteImport.update({
    id: '/case-design',
    path: '/case-design',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)
const AuthenticatedBackOfficeAdvancedDeskRoute =
  AuthenticatedBackOfficeAdvancedDeskRouteImport.update({
    id: '/advanced-desk',
    path: '/advanced-desk',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)
const AuthenticatedAgencyTeamRoute = AuthenticatedAgencyTeamRouteImport.update({
  id: '/agency/team',
  path: '/agency/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgencySettingsRoute =
  AuthenticatedAgencySettingsRouteImport.update({
    id: '/agency/settings',
    path: '/agency/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountProducerProfileRoute =
  AuthenticatedAccountProducerProfileRouteImport.update({
    id: '/account/producer-profile',
    path: '/account/producer-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountMyLandingPageRoute =
  AuthenticatedAccountMyLandingPageRouteImport.update({
    id: '/account/my-landing-page',
    path: '/account/my-landing-page',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountHelpRoute =
  AuthenticatedAccountHelpRouteImport.update({
    id: '/account/help',
    path: '/account/help',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountFaqRoute = AuthenticatedAccountFaqRouteImport.update({
  id: '/account/faq',
  path: '/account/faq',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksFetchNewsRoute = ApiPublicHooksFetchNewsRouteImport.update({
  id: '/api/public/hooks/fetch-news',
  path: '/api/public/hooks/fetch-news',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBackOfficeCaseDesignAdminRoute =
  AuthenticatedBackOfficeCaseDesignAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedBackOfficeCaseDesignRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/back-office': typeof AuthenticatedBackOfficeRouteWithChildren
  '/book-of-business': typeof AuthenticatedBookOfBusinessRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/carrier-sync': typeof AuthenticatedCarrierSyncRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/contracting': typeof AuthenticatedContractingRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/news-feed': typeof AuthenticatedNewsFeedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/nova': typeof AuthenticatedNovaRouteWithChildren
  '/phone': typeof AuthenticatedPhoneRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/post-deal': typeof AuthenticatedPostDealRoute
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/csv-import': typeof AdminCsvImportRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/import-requests': typeof AdminImportRequestsRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$slug': typeof JoinSlugRoute
  '/myagent/$agentSlug': typeof MyagentAgentSlugRoute
  '/signup/agent': typeof SignupAgentRoute
  '/admin/': typeof AdminIndexRoute
  '/account/faq': typeof AuthenticatedAccountFaqRoute
  '/account/help': typeof AuthenticatedAccountHelpRoute
  '/account/my-landing-page': typeof AuthenticatedAccountMyLandingPageRoute
  '/account/producer-profile': typeof AuthenticatedAccountProducerProfileRoute
  '/agency/settings': typeof AuthenticatedAgencySettingsRoute
  '/agency/team': typeof AuthenticatedAgencyTeamRoute
  '/back-office/advanced-desk': typeof AuthenticatedBackOfficeAdvancedDeskRoute
  '/back-office/case-design': typeof AuthenticatedBackOfficeCaseDesignRouteWithChildren
  '/back-office/client-marketing': typeof AuthenticatedBackOfficeClientMarketingRoute
  '/back-office/marketing-tracker': typeof AuthenticatedBackOfficeMarketingTrackerRoute
  '/back-office/recruiting-funnels': typeof AuthenticatedBackOfficeRecruitingFunnelsRoute
  '/back-office/recruiting-tracker': typeof AuthenticatedBackOfficeRecruitingTrackerRoute
  '/contracting/annuity-training': typeof AuthenticatedContractingAnnuityTrainingRoute
  '/contracting/carriers': typeof AuthenticatedContractingCarriersRoute
  '/contracting/commission-grids': typeof AuthenticatedContractingCommissionGridsRoute
  '/contracting/invite': typeof AuthenticatedContractingInviteRoute
  '/contracting/transfers': typeof AuthenticatedContractingTransfersRoute
  '/nova/activity': typeof AuthenticatedNovaActivityRoute
  '/nova/settings': typeof AuthenticatedNovaSettingsRoute
  '/resources/agent-academy': typeof AuthenticatedResourcesAgentAcademyRoute
  '/resources/agent-handbook': typeof AuthenticatedResourcesAgentHandbookRoute
  '/resources/new-agent-guide': typeof AuthenticatedResourcesNewAgentGuideRoute
  '/resources/scripts': typeof AuthenticatedResourcesScriptsRoute
  '/resources/state-licenses': typeof AuthenticatedResourcesStateLicensesRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/nova-pro': typeof AuthenticatedSettingsNovaProRoute
  '/tools/leads': typeof AuthenticatedToolsLeadsRoute
  '/agent/$agentSlug/$templateSlug': typeof AgentAgentSlugTemplateSlugRoute
  '/api/public/funnel-apply': typeof ApiPublicFunnelApplyRoute
  '/api/public/funnel-view': typeof ApiPublicFunnelViewRoute
  '/api/public/landing-lead': typeof ApiPublicLandingLeadRoute
  '/api/public/lead-submit': typeof ApiPublicLeadSubmitRoute
  '/api/public/page-data': typeof ApiPublicPageDataRoute
  '/api/public/waitlist-count': typeof ApiPublicWaitlistCountRoute
  '/api/public/waitlist-signup': typeof ApiPublicWaitlistSignupRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/contracting/': typeof AuthenticatedContractingIndexRoute
  '/back-office/case-design/admin': typeof AuthenticatedBackOfficeCaseDesignAdminRoute
  '/api/public/hooks/fetch-news': typeof ApiPublicHooksFetchNewsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/back-office': typeof AuthenticatedBackOfficeRouteWithChildren
  '/book-of-business': typeof AuthenticatedBookOfBusinessRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/carrier-sync': typeof AuthenticatedCarrierSyncRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/news-feed': typeof AuthenticatedNewsFeedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/nova': typeof AuthenticatedNovaRouteWithChildren
  '/phone': typeof AuthenticatedPhoneRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/post-deal': typeof AuthenticatedPostDealRoute
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/csv-import': typeof AdminCsvImportRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/import-requests': typeof AdminImportRequestsRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$slug': typeof JoinSlugRoute
  '/myagent/$agentSlug': typeof MyagentAgentSlugRoute
  '/signup/agent': typeof SignupAgentRoute
  '/admin': typeof AdminIndexRoute
  '/account/faq': typeof AuthenticatedAccountFaqRoute
  '/account/help': typeof AuthenticatedAccountHelpRoute
  '/account/my-landing-page': typeof AuthenticatedAccountMyLandingPageRoute
  '/account/producer-profile': typeof AuthenticatedAccountProducerProfileRoute
  '/agency/settings': typeof AuthenticatedAgencySettingsRoute
  '/agency/team': typeof AuthenticatedAgencyTeamRoute
  '/back-office/advanced-desk': typeof AuthenticatedBackOfficeAdvancedDeskRoute
  '/back-office/case-design': typeof AuthenticatedBackOfficeCaseDesignRouteWithChildren
  '/back-office/client-marketing': typeof AuthenticatedBackOfficeClientMarketingRoute
  '/back-office/marketing-tracker': typeof AuthenticatedBackOfficeMarketingTrackerRoute
  '/back-office/recruiting-funnels': typeof AuthenticatedBackOfficeRecruitingFunnelsRoute
  '/back-office/recruiting-tracker': typeof AuthenticatedBackOfficeRecruitingTrackerRoute
  '/contracting/annuity-training': typeof AuthenticatedContractingAnnuityTrainingRoute
  '/contracting/carriers': typeof AuthenticatedContractingCarriersRoute
  '/contracting/commission-grids': typeof AuthenticatedContractingCommissionGridsRoute
  '/contracting/invite': typeof AuthenticatedContractingInviteRoute
  '/contracting/transfers': typeof AuthenticatedContractingTransfersRoute
  '/nova/activity': typeof AuthenticatedNovaActivityRoute
  '/nova/settings': typeof AuthenticatedNovaSettingsRoute
  '/resources/agent-academy': typeof AuthenticatedResourcesAgentAcademyRoute
  '/resources/agent-handbook': typeof AuthenticatedResourcesAgentHandbookRoute
  '/resources/new-agent-guide': typeof AuthenticatedResourcesNewAgentGuideRoute
  '/resources/scripts': typeof AuthenticatedResourcesScriptsRoute
  '/resources/state-licenses': typeof AuthenticatedResourcesStateLicensesRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/nova-pro': typeof AuthenticatedSettingsNovaProRoute
  '/tools/leads': typeof AuthenticatedToolsLeadsRoute
  '/agent/$agentSlug/$templateSlug': typeof AgentAgentSlugTemplateSlugRoute
  '/api/public/funnel-apply': typeof ApiPublicFunnelApplyRoute
  '/api/public/funnel-view': typeof ApiPublicFunnelViewRoute
  '/api/public/landing-lead': typeof ApiPublicLandingLeadRoute
  '/api/public/lead-submit': typeof ApiPublicLeadSubmitRoute
  '/api/public/page-data': typeof ApiPublicPageDataRoute
  '/api/public/waitlist-count': typeof ApiPublicWaitlistCountRoute
  '/api/public/waitlist-signup': typeof ApiPublicWaitlistSignupRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/contracting': typeof AuthenticatedContractingIndexRoute
  '/back-office/case-design/admin': typeof AuthenticatedBackOfficeCaseDesignAdminRoute
  '/api/public/hooks/fetch-news': typeof ApiPublicHooksFetchNewsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/back-office': typeof AuthenticatedBackOfficeRouteWithChildren
  '/_authenticated/book-of-business': typeof AuthenticatedBookOfBusinessRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/carrier-sync': typeof AuthenticatedCarrierSyncRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/contracting': typeof AuthenticatedContractingRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/news-feed': typeof AuthenticatedNewsFeedRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/nova': typeof AuthenticatedNovaRouteWithChildren
  '/_authenticated/phone': typeof AuthenticatedPhoneRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/post-deal': typeof AuthenticatedPostDealRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/csv-import': typeof AdminCsvImportRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/import-requests': typeof AdminImportRequestsRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$slug': typeof JoinSlugRoute
  '/myagent/$agentSlug': typeof MyagentAgentSlugRoute
  '/signup_/agent': typeof SignupAgentRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/account/faq': typeof AuthenticatedAccountFaqRoute
  '/_authenticated/account/help': typeof AuthenticatedAccountHelpRoute
  '/_authenticated/account/my-landing-page': typeof AuthenticatedAccountMyLandingPageRoute
  '/_authenticated/account/producer-profile': typeof AuthenticatedAccountProducerProfileRoute
  '/_authenticated/agency/settings': typeof AuthenticatedAgencySettingsRoute
  '/_authenticated/agency/team': typeof AuthenticatedAgencyTeamRoute
  '/_authenticated/back-office/advanced-desk': typeof AuthenticatedBackOfficeAdvancedDeskRoute
  '/_authenticated/back-office/case-design': typeof AuthenticatedBackOfficeCaseDesignRouteWithChildren
  '/_authenticated/back-office/client-marketing': typeof AuthenticatedBackOfficeClientMarketingRoute
  '/_authenticated/back-office/marketing-tracker': typeof AuthenticatedBackOfficeMarketingTrackerRoute
  '/_authenticated/back-office/recruiting-funnels': typeof AuthenticatedBackOfficeRecruitingFunnelsRoute
  '/_authenticated/back-office/recruiting-tracker': typeof AuthenticatedBackOfficeRecruitingTrackerRoute
  '/_authenticated/contracting/annuity-training': typeof AuthenticatedContractingAnnuityTrainingRoute
  '/_authenticated/contracting/carriers': typeof AuthenticatedContractingCarriersRoute
  '/_authenticated/contracting/commission-grids': typeof AuthenticatedContractingCommissionGridsRoute
  '/_authenticated/contracting/invite': typeof AuthenticatedContractingInviteRoute
  '/_authenticated/contracting/transfers': typeof AuthenticatedContractingTransfersRoute
  '/_authenticated/nova/activity': typeof AuthenticatedNovaActivityRoute
  '/_authenticated/nova/settings': typeof AuthenticatedNovaSettingsRoute
  '/_authenticated/resources/agent-academy': typeof AuthenticatedResourcesAgentAcademyRoute
  '/_authenticated/resources/agent-handbook': typeof AuthenticatedResourcesAgentHandbookRoute
  '/_authenticated/resources/new-agent-guide': typeof AuthenticatedResourcesNewAgentGuideRoute
  '/_authenticated/resources/scripts': typeof AuthenticatedResourcesScriptsRoute
  '/_authenticated/resources/state-licenses': typeof AuthenticatedResourcesStateLicensesRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/nova-pro': typeof AuthenticatedSettingsNovaProRoute
  '/_authenticated/tools/leads': typeof AuthenticatedToolsLeadsRoute
  '/agent/$agentSlug/$templateSlug': typeof AgentAgentSlugTemplateSlugRoute
  '/api/public/funnel-apply': typeof ApiPublicFunnelApplyRoute
  '/api/public/funnel-view': typeof ApiPublicFunnelViewRoute
  '/api/public/landing-lead': typeof ApiPublicLandingLeadRoute
  '/api/public/lead-submit': typeof ApiPublicLeadSubmitRoute
  '/api/public/page-data': typeof ApiPublicPageDataRoute
  '/api/public/waitlist-count': typeof ApiPublicWaitlistCountRoute
  '/api/public/waitlist-signup': typeof ApiPublicWaitlistSignupRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/contracting/': typeof AuthenticatedContractingIndexRoute
  '/_authenticated/back-office/case-design/admin': typeof AuthenticatedBackOfficeCaseDesignAdminRoute
  '/api/public/hooks/fetch-news': typeof ApiPublicHooksFetchNewsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ai-assistant'
    | '/analytics'
    | '/announcements'
    | '/back-office'
    | '/book-of-business'
    | '/calendar'
    | '/carrier-sync'
    | '/challenges'
    | '/contracting'
    | '/dashboard'
    | '/finances'
    | '/leaderboard'
    | '/news-feed'
    | '/notifications'
    | '/nova'
    | '/phone'
    | '/pipeline'
    | '/post-deal'
    | '/resources'
    | '/team'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/billing'
    | '/admin/carriers'
    | '/admin/commissions'
    | '/admin/contracts'
    | '/admin/csv-import'
    | '/admin/hierarchy'
    | '/admin/import-requests'
    | '/admin/migration'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/join/$slug'
    | '/myagent/$agentSlug'
    | '/signup/agent'
    | '/admin/'
    | '/account/faq'
    | '/account/help'
    | '/account/my-landing-page'
    | '/account/producer-profile'
    | '/agency/settings'
    | '/agency/team'
    | '/back-office/advanced-desk'
    | '/back-office/case-design'
    | '/back-office/client-marketing'
    | '/back-office/marketing-tracker'
    | '/back-office/recruiting-funnels'
    | '/back-office/recruiting-tracker'
    | '/contracting/annuity-training'
    | '/contracting/carriers'
    | '/contracting/commission-grids'
    | '/contracting/invite'
    | '/contracting/transfers'
    | '/nova/activity'
    | '/nova/settings'
    | '/resources/agent-academy'
    | '/resources/agent-handbook'
    | '/resources/new-agent-guide'
    | '/resources/scripts'
    | '/resources/state-licenses'
    | '/settings/billing'
    | '/settings/nova-pro'
    | '/tools/leads'
    | '/agent/$agentSlug/$templateSlug'
    | '/api/public/funnel-apply'
    | '/api/public/funnel-view'
    | '/api/public/landing-lead'
    | '/api/public/lead-submit'
    | '/api/public/page-data'
    | '/api/public/waitlist-count'
    | '/api/public/waitlist-signup'
    | '/api/stripe/webhook'
    | '/lovable/email/suppression'
    | '/contracting/'
    | '/back-office/case-design/admin'
    | '/api/public/hooks/fetch-news'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ai-assistant'
    | '/analytics'
    | '/announcements'
    | '/back-office'
    | '/book-of-business'
    | '/calendar'
    | '/carrier-sync'
    | '/challenges'
    | '/dashboard'
    | '/finances'
    | '/leaderboard'
    | '/news-feed'
    | '/notifications'
    | '/nova'
    | '/phone'
    | '/pipeline'
    | '/post-deal'
    | '/resources'
    | '/team'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/billing'
    | '/admin/carriers'
    | '/admin/commissions'
    | '/admin/contracts'
    | '/admin/csv-import'
    | '/admin/hierarchy'
    | '/admin/import-requests'
    | '/admin/migration'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/join/$slug'
    | '/myagent/$agentSlug'
    | '/signup/agent'
    | '/admin'
    | '/account/faq'
    | '/account/help'
    | '/account/my-landing-page'
    | '/account/producer-profile'
    | '/agency/settings'
    | '/agency/team'
    | '/back-office/advanced-desk'
    | '/back-office/case-design'
    | '/back-office/client-marketing'
    | '/back-office/marketing-tracker'
    | '/back-office/recruiting-funnels'
    | '/back-office/recruiting-tracker'
    | '/contracting/annuity-training'
    | '/contracting/carriers'
    | '/contracting/commission-grids'
    | '/contracting/invite'
    | '/contracting/transfers'
    | '/nova/activity'
    | '/nova/settings'
    | '/resources/agent-academy'
    | '/resources/agent-handbook'
    | '/resources/new-agent-guide'
    | '/resources/scripts'
    | '/resources/state-licenses'
    | '/settings/billing'
    | '/settings/nova-pro'
    | '/tools/leads'
    | '/agent/$agentSlug/$templateSlug'
    | '/api/public/funnel-apply'
    | '/api/public/funnel-view'
    | '/api/public/landing-lead'
    | '/api/public/lead-submit'
    | '/api/public/page-data'
    | '/api/public/waitlist-count'
    | '/api/public/waitlist-signup'
    | '/api/stripe/webhook'
    | '/lovable/email/suppression'
    | '/contracting'
    | '/back-office/case-design/admin'
    | '/api/public/hooks/fetch-news'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/analytics'
    | '/_authenticated/announcements'
    | '/_authenticated/back-office'
    | '/_authenticated/book-of-business'
    | '/_authenticated/calendar'
    | '/_authenticated/carrier-sync'
    | '/_authenticated/challenges'
    | '/_authenticated/contracting'
    | '/_authenticated/dashboard'
    | '/_authenticated/finances'
    | '/_authenticated/leaderboard'
    | '/_authenticated/news-feed'
    | '/_authenticated/notifications'
    | '/_authenticated/nova'
    | '/_authenticated/phone'
    | '/_authenticated/pipeline'
    | '/_authenticated/post-deal'
    | '/_authenticated/resources'
    | '/_authenticated/team'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/billing'
    | '/admin/carriers'
    | '/admin/commissions'
    | '/admin/contracts'
    | '/admin/csv-import'
    | '/admin/hierarchy'
    | '/admin/import-requests'
    | '/admin/migration'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/join/$slug'
    | '/myagent/$agentSlug'
    | '/signup_/agent'
    | '/admin/'
    | '/_authenticated/account/faq'
    | '/_authenticated/account/help'
    | '/_authenticated/account/my-landing-page'
    | '/_authenticated/account/producer-profile'
    | '/_authenticated/agency/settings'
    | '/_authenticated/agency/team'
    | '/_authenticated/back-office/advanced-desk'
    | '/_authenticated/back-office/case-design'
    | '/_authenticated/back-office/client-marketing'
    | '/_authenticated/back-office/marketing-tracker'
    | '/_authenticated/back-office/recruiting-funnels'
    | '/_authenticated/back-office/recruiting-tracker'
    | '/_authenticated/contracting/annuity-training'
    | '/_authenticated/contracting/carriers'
    | '/_authenticated/contracting/commission-grids'
    | '/_authenticated/contracting/invite'
    | '/_authenticated/contracting/transfers'
    | '/_authenticated/nova/activity'
    | '/_authenticated/nova/settings'
    | '/_authenticated/resources/agent-academy'
    | '/_authenticated/resources/agent-handbook'
    | '/_authenticated/resources/new-agent-guide'
    | '/_authenticated/resources/scripts'
    | '/_authenticated/resources/state-licenses'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/nova-pro'
    | '/_authenticated/tools/leads'
    | '/agent/$agentSlug/$templateSlug'
    | '/api/public/funnel-apply'
    | '/api/public/funnel-view'
    | '/api/public/landing-lead'
    | '/api/public/lead-submit'
    | '/api/public/page-data'
    | '/api/public/waitlist-count'
    | '/api/public/waitlist-signup'
    | '/api/stripe/webhook'
    | '/lovable/email/suppression'
    | '/_authenticated/contracting/'
    | '/_authenticated/back-office/case-design/admin'
    | '/api/public/hooks/fetch-news'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinSlugRoute: typeof JoinSlugRoute
  MyagentAgentSlugRoute: typeof MyagentAgentSlugRoute
  SignupAgentRoute: typeof SignupAgentRoute
  AgentAgentSlugTemplateSlugRoute: typeof AgentAgentSlugTemplateSlugRoute
  ApiPublicFunnelApplyRoute: typeof ApiPublicFunnelApplyRoute
  ApiPublicFunnelViewRoute: typeof ApiPublicFunnelViewRoute
  ApiPublicLandingLeadRoute: typeof ApiPublicLandingLeadRoute
  ApiPublicLeadSubmitRoute: typeof ApiPublicLeadSubmitRoute
  ApiPublicPageDataRoute: typeof ApiPublicPageDataRoute
  ApiPublicWaitlistCountRoute: typeof ApiPublicWaitlistCountRoute
  ApiPublicWaitlistSignupRoute: typeof ApiPublicWaitlistSignupRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksFetchNewsRoute: typeof ApiPublicHooksFetchNewsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/signup_/agent': {
      id: '/signup_/agent'
      path: '/signup/agent'
      fullPath: '/signup/agent'
      preLoaderRoute: typeof SignupAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myagent/$agentSlug': {
      id: '/myagent/$agentSlug'
      path: '/myagent/$agentSlug'
      fullPath: '/myagent/$agentSlug'
      preLoaderRoute: typeof MyagentAgentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/migration': {
      id: '/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AdminMigrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import-requests': {
      id: '/admin/import-requests'
      path: '/import-requests'
      fullPath: '/admin/import-requests'
      preLoaderRoute: typeof AdminImportRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hierarchy': {
      id: '/admin/hierarchy'
      path: '/hierarchy'
      fullPath: '/admin/hierarchy'
      preLoaderRoute: typeof AdminHierarchyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/csv-import': {
      id: '/admin/csv-import'
      path: '/csv-import'
      fullPath: '/admin/csv-import'
      preLoaderRoute: typeof AdminCsvImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carriers': {
      id: '/admin/carriers'
      path: '/carriers'
      fullPath: '/admin/carriers'
      preLoaderRoute: typeof AdminCarriersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/post-deal': {
      id: '/_authenticated/post-deal'
      path: '/post-deal'
      fullPath: '/post-deal'
      preLoaderRoute: typeof AuthenticatedPostDealRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phone': {
      id: '/_authenticated/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof AuthenticatedPhoneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nova': {
      id: '/_authenticated/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof AuthenticatedNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/news-feed': {
      id: '/_authenticated/news-feed'
      path: '/news-feed'
      fullPath: '/news-feed'
      preLoaderRoute: typeof AuthenticatedNewsFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracting': {
      id: '/_authenticated/contracting'
      path: '/contracting'
      fullPath: '/contracting'
      preLoaderRoute: typeof AuthenticatedContractingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/carrier-sync': {
      id: '/_authenticated/carrier-sync'
      path: '/carrier-sync'
      fullPath: '/carrier-sync'
      preLoaderRoute: typeof AuthenticatedCarrierSyncRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/book-of-business': {
      id: '/_authenticated/book-of-business'
      path: '/book-of-business'
      fullPath: '/book-of-business'
      preLoaderRoute: typeof AuthenticatedBookOfBusinessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/back-office': {
      id: '/_authenticated/back-office'
      path: '/back-office'
      fullPath: '/back-office'
      preLoaderRoute: typeof AuthenticatedBackOfficeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracting/': {
      id: '/_authenticated/contracting/'
      path: '/'
      fullPath: '/contracting/'
      preLoaderRoute: typeof AuthenticatedContractingIndexRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist-signup': {
      id: '/api/public/waitlist-signup'
      path: '/api/public/waitlist-signup'
      fullPath: '/api/public/waitlist-signup'
      preLoaderRoute: typeof ApiPublicWaitlistSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist-count': {
      id: '/api/public/waitlist-count'
      path: '/api/public/waitlist-count'
      fullPath: '/api/public/waitlist-count'
      preLoaderRoute: typeof ApiPublicWaitlistCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/page-data': {
      id: '/api/public/page-data'
      path: '/api/public/page-data'
      fullPath: '/api/public/page-data'
      preLoaderRoute: typeof ApiPublicPageDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-submit': {
      id: '/api/public/lead-submit'
      path: '/api/public/lead-submit'
      fullPath: '/api/public/lead-submit'
      preLoaderRoute: typeof ApiPublicLeadSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/landing-lead': {
      id: '/api/public/landing-lead'
      path: '/api/public/landing-lead'
      fullPath: '/api/public/landing-lead'
      preLoaderRoute: typeof ApiPublicLandingLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/funnel-view': {
      id: '/api/public/funnel-view'
      path: '/api/public/funnel-view'
      fullPath: '/api/public/funnel-view'
      preLoaderRoute: typeof ApiPublicFunnelViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/funnel-apply': {
      id: '/api/public/funnel-apply'
      path: '/api/public/funnel-apply'
      fullPath: '/api/public/funnel-apply'
      preLoaderRoute: typeof ApiPublicFunnelApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$agentSlug/$templateSlug': {
      id: '/agent/$agentSlug/$templateSlug'
      path: '/agent/$agentSlug/$templateSlug'
      fullPath: '/agent/$agentSlug/$templateSlug'
      preLoaderRoute: typeof AgentAgentSlugTemplateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools/leads': {
      id: '/_authenticated/tools/leads'
      path: '/tools/leads'
      fullPath: '/tools/leads'
      preLoaderRoute: typeof AuthenticatedToolsLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/nova-pro': {
      id: '/_authenticated/settings/nova-pro'
      path: '/settings/nova-pro'
      fullPath: '/settings/nova-pro'
      preLoaderRoute: typeof AuthenticatedSettingsNovaProRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources/state-licenses': {
      id: '/_authenticated/resources/state-licenses'
      path: '/state-licenses'
      fullPath: '/resources/state-licenses'
      preLoaderRoute: typeof AuthenticatedResourcesStateLicensesRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/resources/scripts': {
      id: '/_authenticated/resources/scripts'
      path: '/scripts'
      fullPath: '/resources/scripts'
      preLoaderRoute: typeof AuthenticatedResourcesScriptsRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/resources/new-agent-guide': {
      id: '/_authenticated/resources/new-agent-guide'
      path: '/new-agent-guide'
      fullPath: '/resources/new-agent-guide'
      preLoaderRoute: typeof AuthenticatedResourcesNewAgentGuideRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/resources/agent-handbook': {
      id: '/_authenticated/resources/agent-handbook'
      path: '/agent-handbook'
      fullPath: '/resources/agent-handbook'
      preLoaderRoute: typeof AuthenticatedResourcesAgentHandbookRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/resources/agent-academy': {
      id: '/_authenticated/resources/agent-academy'
      path: '/agent-academy'
      fullPath: '/resources/agent-academy'
      preLoaderRoute: typeof AuthenticatedResourcesAgentAcademyRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/nova/settings': {
      id: '/_authenticated/nova/settings'
      path: '/settings'
      fullPath: '/nova/settings'
      preLoaderRoute: typeof AuthenticatedNovaSettingsRouteImport
      parentRoute: typeof AuthenticatedNovaRoute
    }
    '/_authenticated/nova/activity': {
      id: '/_authenticated/nova/activity'
      path: '/activity'
      fullPath: '/nova/activity'
      preLoaderRoute: typeof AuthenticatedNovaActivityRouteImport
      parentRoute: typeof AuthenticatedNovaRoute
    }
    '/_authenticated/contracting/transfers': {
      id: '/_authenticated/contracting/transfers'
      path: '/transfers'
      fullPath: '/contracting/transfers'
      preLoaderRoute: typeof AuthenticatedContractingTransfersRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/contracting/invite': {
      id: '/_authenticated/contracting/invite'
      path: '/invite'
      fullPath: '/contracting/invite'
      preLoaderRoute: typeof AuthenticatedContractingInviteRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/contracting/commission-grids': {
      id: '/_authenticated/contracting/commission-grids'
      path: '/commission-grids'
      fullPath: '/contracting/commission-grids'
      preLoaderRoute: typeof AuthenticatedContractingCommissionGridsRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/contracting/carriers': {
      id: '/_authenticated/contracting/carriers'
      path: '/carriers'
      fullPath: '/contracting/carriers'
      preLoaderRoute: typeof AuthenticatedContractingCarriersRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/contracting/annuity-training': {
      id: '/_authenticated/contracting/annuity-training'
      path: '/annuity-training'
      fullPath: '/contracting/annuity-training'
      preLoaderRoute: typeof AuthenticatedContractingAnnuityTrainingRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/back-office/recruiting-tracker': {
      id: '/_authenticated/back-office/recruiting-tracker'
      path: '/recruiting-tracker'
      fullPath: '/back-office/recruiting-tracker'
      preLoaderRoute: typeof AuthenticatedBackOfficeRecruitingTrackerRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
    '/_authenticated/back-office/recruiting-funnels': {
      id: '/_authenticated/back-office/recruiting-funnels'
      path: '/recruiting-funnels'
      fullPath: '/back-office/recruiting-funnels'
      preLoaderRoute: typeof AuthenticatedBackOfficeRecruitingFunnelsRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
    '/_authenticated/back-office/marketing-tracker': {
      id: '/_authenticated/back-office/marketing-tracker'
      path: '/marketing-tracker'
      fullPath: '/back-office/marketing-tracker'
      preLoaderRoute: typeof AuthenticatedBackOfficeMarketingTrackerRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
    '/_authenticated/back-office/client-marketing': {
      id: '/_authenticated/back-office/client-marketing'
      path: '/client-marketing'
      fullPath: '/back-office/client-marketing'
      preLoaderRoute: typeof AuthenticatedBackOfficeClientMarketingRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
    '/_authenticated/back-office/case-design': {
      id: '/_authenticated/back-office/case-design'
      path: '/case-design'
      fullPath: '/back-office/case-design'
      preLoaderRoute: typeof AuthenticatedBackOfficeCaseDesignRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
    '/_authenticated/back-office/advanced-desk': {
      id: '/_authenticated/back-office/advanced-desk'
      path: '/advanced-desk'
      fullPath: '/back-office/advanced-desk'
      preLoaderRoute: typeof AuthenticatedBackOfficeAdvancedDeskRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
    '/_authenticated/agency/team': {
      id: '/_authenticated/agency/team'
      path: '/agency/team'
      fullPath: '/agency/team'
      preLoaderRoute: typeof AuthenticatedAgencyTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agency/settings': {
      id: '/_authenticated/agency/settings'
      path: '/agency/settings'
      fullPath: '/agency/settings'
      preLoaderRoute: typeof AuthenticatedAgencySettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/producer-profile': {
      id: '/_authenticated/account/producer-profile'
      path: '/account/producer-profile'
      fullPath: '/account/producer-profile'
      preLoaderRoute: typeof AuthenticatedAccountProducerProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/my-landing-page': {
      id: '/_authenticated/account/my-landing-page'
      path: '/account/my-landing-page'
      fullPath: '/account/my-landing-page'
      preLoaderRoute: typeof AuthenticatedAccountMyLandingPageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/help': {
      id: '/_authenticated/account/help'
      path: '/account/help'
      fullPath: '/account/help'
      preLoaderRoute: typeof AuthenticatedAccountHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/faq': {
      id: '/_authenticated/account/faq'
      path: '/account/faq'
      fullPath: '/account/faq'
      preLoaderRoute: typeof AuthenticatedAccountFaqRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fetch-news': {
      id: '/api/public/hooks/fetch-news'
      path: '/api/public/hooks/fetch-news'
      fullPath: '/api/public/hooks/fetch-news'
      preLoaderRoute: typeof ApiPublicHooksFetchNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/back-office/case-design/admin': {
      id: '/_authenticated/back-office/case-design/admin'
      path: '/admin'
      fullPath: '/back-office/case-design/admin'
      preLoaderRoute: typeof AuthenticatedBackOfficeCaseDesignAdminRouteImport
      parentRoute: typeof AuthenticatedBackOfficeCaseDesignRoute
    }
  }
}

interface AuthenticatedBackOfficeCaseDesignRouteChildren {
  AuthenticatedBackOfficeCaseDesignAdminRoute: typeof AuthenticatedBackOfficeCaseDesignAdminRoute
}

const AuthenticatedBackOfficeCaseDesignRouteChildren: AuthenticatedBackOfficeCaseDesignRouteChildren =
  {
    AuthenticatedBackOfficeCaseDesignAdminRoute:
      AuthenticatedBackOfficeCaseDesignAdminRoute,
  }

const AuthenticatedBackOfficeCaseDesignRouteWithChildren =
  AuthenticatedBackOfficeCaseDesignRoute._addFileChildren(
    AuthenticatedBackOfficeCaseDesignRouteChildren,
  )

interface AuthenticatedBackOfficeRouteChildren {
  AuthenticatedBackOfficeAdvancedDeskRoute: typeof AuthenticatedBackOfficeAdvancedDeskRoute
  AuthenticatedBackOfficeCaseDesignRoute: typeof AuthenticatedBackOfficeCaseDesignRouteWithChildren
  AuthenticatedBackOfficeClientMarketingRoute: typeof AuthenticatedBackOfficeClientMarketingRoute
  AuthenticatedBackOfficeMarketingTrackerRoute: typeof AuthenticatedBackOfficeMarketingTrackerRoute
  AuthenticatedBackOfficeRecruitingFunnelsRoute: typeof AuthenticatedBackOfficeRecruitingFunnelsRoute
  AuthenticatedBackOfficeRecruitingTrackerRoute: typeof AuthenticatedBackOfficeRecruitingTrackerRoute
}

const AuthenticatedBackOfficeRouteChildren: AuthenticatedBackOfficeRouteChildren =
  {
    AuthenticatedBackOfficeAdvancedDeskRoute:
      AuthenticatedBackOfficeAdvancedDeskRoute,
    AuthenticatedBackOfficeCaseDesignRoute:
      AuthenticatedBackOfficeCaseDesignRouteWithChildren,
    AuthenticatedBackOfficeClientMarketingRoute:
      AuthenticatedBackOfficeClientMarketingRoute,
    AuthenticatedBackOfficeMarketingTrackerRoute:
      AuthenticatedBackOfficeMarketingTrackerRoute,
    AuthenticatedBackOfficeRecruitingFunnelsRoute:
      AuthenticatedBackOfficeRecruitingFunnelsRoute,
    AuthenticatedBackOfficeRecruitingTrackerRoute:
      AuthenticatedBackOfficeRecruitingTrackerRoute,
  }

const AuthenticatedBackOfficeRouteWithChildren =
  AuthenticatedBackOfficeRoute._addFileChildren(
    AuthenticatedBackOfficeRouteChildren,
  )

interface AuthenticatedContractingRouteChildren {
  AuthenticatedContractingAnnuityTrainingRoute: typeof AuthenticatedContractingAnnuityTrainingRoute
  AuthenticatedContractingCarriersRoute: typeof AuthenticatedContractingCarriersRoute
  AuthenticatedContractingCommissionGridsRoute: typeof AuthenticatedContractingCommissionGridsRoute
  AuthenticatedContractingInviteRoute: typeof AuthenticatedContractingInviteRoute
  AuthenticatedContractingTransfersRoute: typeof AuthenticatedContractingTransfersRoute
  AuthenticatedContractingIndexRoute: typeof AuthenticatedContractingIndexRoute
}

const AuthenticatedContractingRouteChildren: AuthenticatedContractingRouteChildren =
  {
    AuthenticatedContractingAnnuityTrainingRoute:
      AuthenticatedContractingAnnuityTrainingRoute,
    AuthenticatedContractingCarriersRoute:
      AuthenticatedContractingCarriersRoute,
    AuthenticatedContractingCommissionGridsRoute:
      AuthenticatedContractingCommissionGridsRoute,
    AuthenticatedContractingInviteRoute: AuthenticatedContractingInviteRoute,
    AuthenticatedContractingTransfersRoute:
      AuthenticatedContractingTransfersRoute,
    AuthenticatedContractingIndexRoute: AuthenticatedContractingIndexRoute,
  }

const AuthenticatedContractingRouteWithChildren =
  AuthenticatedContractingRoute._addFileChildren(
    AuthenticatedContractingRouteChildren,
  )

interface AuthenticatedNovaRouteChildren {
  AuthenticatedNovaActivityRoute: typeof AuthenticatedNovaActivityRoute
  AuthenticatedNovaSettingsRoute: typeof AuthenticatedNovaSettingsRoute
}

const AuthenticatedNovaRouteChildren: AuthenticatedNovaRouteChildren = {
  AuthenticatedNovaActivityRoute: AuthenticatedNovaActivityRoute,
  AuthenticatedNovaSettingsRoute: AuthenticatedNovaSettingsRoute,
}

const AuthenticatedNovaRouteWithChildren =
  AuthenticatedNovaRoute._addFileChildren(AuthenticatedNovaRouteChildren)

interface AuthenticatedResourcesRouteChildren {
  AuthenticatedResourcesAgentAcademyRoute: typeof AuthenticatedResourcesAgentAcademyRoute
  AuthenticatedResourcesAgentHandbookRoute: typeof AuthenticatedResourcesAgentHandbookRoute
  AuthenticatedResourcesNewAgentGuideRoute: typeof AuthenticatedResourcesNewAgentGuideRoute
  AuthenticatedResourcesScriptsRoute: typeof AuthenticatedResourcesScriptsRoute
  AuthenticatedResourcesStateLicensesRoute: typeof AuthenticatedResourcesStateLicensesRoute
}

const AuthenticatedResourcesRouteChildren: AuthenticatedResourcesRouteChildren =
  {
    AuthenticatedResourcesAgentAcademyRoute:
      AuthenticatedResourcesAgentAcademyRoute,
    AuthenticatedResourcesAgentHandbookRoute:
      AuthenticatedResourcesAgentHandbookRoute,
    AuthenticatedResourcesNewAgentGuideRoute:
      AuthenticatedResourcesNewAgentGuideRoute,
    AuthenticatedResourcesScriptsRoute: AuthenticatedResourcesScriptsRoute,
    AuthenticatedResourcesStateLicensesRoute:
      AuthenticatedResourcesStateLicensesRoute,
  }

const AuthenticatedResourcesRouteWithChildren =
  AuthenticatedResourcesRoute._addFileChildren(
    AuthenticatedResourcesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedBackOfficeRoute: typeof AuthenticatedBackOfficeRouteWithChildren
  AuthenticatedBookOfBusinessRoute: typeof AuthenticatedBookOfBusinessRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCarrierSyncRoute: typeof AuthenticatedCarrierSyncRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedContractingRoute: typeof AuthenticatedContractingRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedNewsFeedRoute: typeof AuthenticatedNewsFeedRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedNovaRoute: typeof AuthenticatedNovaRouteWithChildren
  AuthenticatedPhoneRoute: typeof AuthenticatedPhoneRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPostDealRoute: typeof AuthenticatedPostDealRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedAccountFaqRoute: typeof AuthenticatedAccountFaqRoute
  AuthenticatedAccountHelpRoute: typeof AuthenticatedAccountHelpRoute
  AuthenticatedAccountMyLandingPageRoute: typeof AuthenticatedAccountMyLandingPageRoute
  AuthenticatedAccountProducerProfileRoute: typeof AuthenticatedAccountProducerProfileRoute
  AuthenticatedAgencySettingsRoute: typeof AuthenticatedAgencySettingsRoute
  AuthenticatedAgencyTeamRoute: typeof AuthenticatedAgencyTeamRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsNovaProRoute: typeof AuthenticatedSettingsNovaProRoute
  AuthenticatedToolsLeadsRoute: typeof AuthenticatedToolsLeadsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedBackOfficeRoute: AuthenticatedBackOfficeRouteWithChildren,
  AuthenticatedBookOfBusinessRoute: AuthenticatedBookOfBusinessRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCarrierSyncRoute: AuthenticatedCarrierSyncRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedContractingRoute: AuthenticatedContractingRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedNewsFeedRoute: AuthenticatedNewsFeedRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedNovaRoute: AuthenticatedNovaRouteWithChildren,
  AuthenticatedPhoneRoute: AuthenticatedPhoneRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPostDealRoute: AuthenticatedPostDealRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedAccountFaqRoute: AuthenticatedAccountFaqRoute,
  AuthenticatedAccountHelpRoute: AuthenticatedAccountHelpRoute,
  AuthenticatedAccountMyLandingPageRoute:
    AuthenticatedAccountMyLandingPageRoute,
  AuthenticatedAccountProducerProfileRoute:
    AuthenticatedAccountProducerProfileRoute,
  AuthenticatedAgencySettingsRoute: AuthenticatedAgencySettingsRoute,
  AuthenticatedAgencyTeamRoute: AuthenticatedAgencyTeamRoute,
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsNovaProRoute: AuthenticatedSettingsNovaProRoute,
  AuthenticatedToolsLeadsRoute: AuthenticatedToolsLeadsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCarriersRoute: typeof AdminCarriersRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminCsvImportRoute: typeof AdminCsvImportRoute
  AdminHierarchyRoute: typeof AdminHierarchyRoute
  AdminImportRequestsRoute: typeof AdminImportRequestsRoute
  AdminMigrationRoute: typeof AdminMigrationRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCarriersRoute: AdminCarriersRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminCsvImportRoute: AdminCsvImportRoute,
  AdminHierarchyRoute: AdminHierarchyRoute,
  AdminImportRequestsRoute: AdminImportRequestsRoute,
  AdminMigrationRoute: AdminMigrationRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinSlugRoute: JoinSlugRoute,
  MyagentAgentSlugRoute: MyagentAgentSlugRoute,
  SignupAgentRoute: SignupAgentRoute,
  AgentAgentSlugTemplateSlugRoute: AgentAgentSlugTemplateSlugRoute,
  ApiPublicFunnelApplyRoute: ApiPublicFunnelApplyRoute,
  ApiPublicFunnelViewRoute: ApiPublicFunnelViewRoute,
  ApiPublicLandingLeadRoute: ApiPublicLandingLeadRoute,
  ApiPublicLeadSubmitRoute: ApiPublicLeadSubmitRoute,
  ApiPublicPageDataRoute: ApiPublicPageDataRoute,
  ApiPublicWaitlistCountRoute: ApiPublicWaitlistCountRoute,
  ApiPublicWaitlistSignupRoute: ApiPublicWaitlistSignupRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksFetchNewsRoute: ApiPublicHooksFetchNewsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
