/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSophaiRouteImport } from './routes/_authenticated/sophai'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedPostDealRouteImport } from './routes/_authenticated/post-deal'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPhoneRouteImport } from './routes/_authenticated/phone'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNewsFeedRouteImport } from './routes/_authenticated/news-feed'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractingRouteImport } from './routes/_authenticated/contracting'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBookOfBusinessRouteImport } from './routes/_authenticated/book-of-business'
import { Route as AuthenticatedBackOfficeRouteImport } from './routes/_authenticated/back-office'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedContractingIndexRouteImport } from './routes/_authenticated/contracting/index'
import { Route as AuthenticatedSophaiSettingsRouteImport } from './routes/_authenticated/sophai/settings'
import { Route as AuthenticatedSophaiActivityRouteImport } from './routes/_authenticated/sophai/activity'
import { Route as AuthenticatedResourcesStateLicensesRouteImport } from './routes/_authenticated/resources/state-licenses'
import { Route as AuthenticatedResourcesScriptsRouteImport } from './routes/_authenticated/resources/scripts'
import { Route as AuthenticatedResourcesNewAgentGuideRouteImport } from './routes/_authenticated/resources/new-agent-guide'
import { Route as AuthenticatedResourcesAgentHandbookRouteImport } from './routes/_authenticated/resources/agent-handbook'
import { Route as AuthenticatedResourcesAgentAcademyRouteImport } from './routes/_authenticated/resources/agent-academy'
import { Route as AuthenticatedContractingTransfersRouteImport } from './routes/_authenticated/contracting/transfers'
import { Route as AuthenticatedContractingInviteRouteImport } from './routes/_authenticated/contracting/invite'
import { Route as AuthenticatedContractingCommissionGridsRouteImport } from './routes/_authenticated/contracting/commission-grids'
import { Route as AuthenticatedContractingCarriersRouteImport } from './routes/_authenticated/contracting/carriers'
import { Route as AuthenticatedContractingAnnuityTrainingRouteImport } from './routes/_authenticated/contracting/annuity-training'
import { Route as AuthenticatedBackOfficeRecruitingTrackerRouteImport } from './routes/_authenticated/back-office/recruiting-tracker'
import { Route as AuthenticatedBackOfficeRecruitingFunnelsRouteImport } from './routes/_authenticated/back-office/recruiting-funnels'
import { Route as AuthenticatedBackOfficeClientMarketingRouteImport } from './routes/_authenticated/back-office/client-marketing'
import { Route as AuthenticatedBackOfficeCaseDesignRouteImport } from './routes/_authenticated/back-office/case-design'
import { Route as AuthenticatedBackOfficeAdvancedDeskRouteImport } from './routes/_authenticated/back-office/advanced-desk'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSophaiRoute = AuthenticatedSophaiRouteImport.update({
  id: '/sophai',
  path: '/sophai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostDealRoute = AuthenticatedPostDealRouteImport.update({
  id: '/post-deal',
  path: '/post-deal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhoneRoute = AuthenticatedPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNewsFeedRoute = AuthenticatedNewsFeedRouteImport.update({
  id: '/news-feed',
  path: '/news-feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContractingRoute =
  AuthenticatedContractingRouteImport.update({
    id: '/contracting',
    path: '/contracting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookOfBusinessRoute =
  AuthenticatedBookOfBusinessRouteImport.update({
    id: '/book-of-business',
    path: '/book-of-business',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBackOfficeRoute = AuthenticatedBackOfficeRouteImport.update({
  id: '/back-office',
  path: '/back-office',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractingIndexRoute =
  AuthenticatedContractingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedSophaiSettingsRoute =
  AuthenticatedSophaiSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSophaiRoute,
  } as any)
const AuthenticatedSophaiActivityRoute =
  AuthenticatedSophaiActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedSophaiRoute,
  } as any)
const AuthenticatedResourcesStateLicensesRoute =
  AuthenticatedResourcesStateLicensesRouteImport.update({
    id: '/state-licenses',
    path: '/state-licenses',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesScriptsRoute =
  AuthenticatedResourcesScriptsRouteImport.update({
    id: '/scripts',
    path: '/scripts',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesNewAgentGuideRoute =
  AuthenticatedResourcesNewAgentGuideRouteImport.update({
    id: '/new-agent-guide',
    path: '/new-agent-guide',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesAgentHandbookRoute =
  AuthenticatedResourcesAgentHandbookRouteImport.update({
    id: '/agent-handbook',
    path: '/agent-handbook',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesAgentAcademyRoute =
  AuthenticatedResourcesAgentAcademyRouteImport.update({
    id: '/agent-academy',
    path: '/agent-academy',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedContractingTransfersRoute =
  AuthenticatedContractingTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedContractingInviteRoute =
  AuthenticatedContractingInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedContractingCommissionGridsRoute =
  AuthenticatedContractingCommissionGridsRouteImport.update({
    id: '/commission-grids',
    path: '/commission-grids',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedContractingCarriersRoute =
  AuthenticatedContractingCarriersRouteImport.update({
    id: '/carriers',
    path: '/carriers',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedContractingAnnuityTrainingRoute =
  AuthenticatedContractingAnnuityTrainingRouteImport.update({
    id: '/annuity-training',
    path: '/annuity-training',
    getParentRoute: () => AuthenticatedContractingRoute,
  } as any)
const AuthenticatedBackOfficeRecruitingTrackerRoute =
  AuthenticatedBackOfficeRecruitingTrackerRouteImport.update({
    id: '/recruiting-tracker',
    path: '/recruiting-tracker',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)
const AuthenticatedBackOfficeRecruitingFunnelsRoute =
  AuthenticatedBackOfficeRecruitingFunnelsRouteImport.update({
    id: '/recruiting-funnels',
    path: '/recruiting-funnels',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)
const AuthenticatedBackOfficeClientMarketingRoute =
  AuthenticatedBackOfficeClientMarketingRouteImport.update({
    id: '/client-marketing',
    path: '/client-marketing',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)
const AuthenticatedBackOfficeCaseDesignRoute =
  AuthenticatedBackOfficeCaseDesignRouteImport.update({
    id: '/case-design',
    path: '/case-design',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)
const AuthenticatedBackOfficeAdvancedDeskRoute =
  AuthenticatedBackOfficeAdvancedDeskRouteImport.update({
    id: '/advanced-desk',
    path: '/advanced-desk',
    getParentRoute: () => AuthenticatedBackOfficeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/back-office': typeof AuthenticatedBackOfficeRouteWithChildren
  '/book-of-business': typeof AuthenticatedBookOfBusinessRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/contracting': typeof AuthenticatedContractingRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/news-feed': typeof AuthenticatedNewsFeedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/phone': typeof AuthenticatedPhoneRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/post-deal': typeof AuthenticatedPostDealRoute
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/sophai': typeof AuthenticatedSophaiRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/back-office/advanced-desk': typeof AuthenticatedBackOfficeAdvancedDeskRoute
  '/back-office/case-design': typeof AuthenticatedBackOfficeCaseDesignRoute
  '/back-office/client-marketing': typeof AuthenticatedBackOfficeClientMarketingRoute
  '/back-office/recruiting-funnels': typeof AuthenticatedBackOfficeRecruitingFunnelsRoute
  '/back-office/recruiting-tracker': typeof AuthenticatedBackOfficeRecruitingTrackerRoute
  '/contracting/annuity-training': typeof AuthenticatedContractingAnnuityTrainingRoute
  '/contracting/carriers': typeof AuthenticatedContractingCarriersRoute
  '/contracting/commission-grids': typeof AuthenticatedContractingCommissionGridsRoute
  '/contracting/invite': typeof AuthenticatedContractingInviteRoute
  '/contracting/transfers': typeof AuthenticatedContractingTransfersRoute
  '/resources/agent-academy': typeof AuthenticatedResourcesAgentAcademyRoute
  '/resources/agent-handbook': typeof AuthenticatedResourcesAgentHandbookRoute
  '/resources/new-agent-guide': typeof AuthenticatedResourcesNewAgentGuideRoute
  '/resources/scripts': typeof AuthenticatedResourcesScriptsRoute
  '/resources/state-licenses': typeof AuthenticatedResourcesStateLicensesRoute
  '/sophai/activity': typeof AuthenticatedSophaiActivityRoute
  '/sophai/settings': typeof AuthenticatedSophaiSettingsRoute
  '/contracting/': typeof AuthenticatedContractingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/back-office': typeof AuthenticatedBackOfficeRouteWithChildren
  '/book-of-business': typeof AuthenticatedBookOfBusinessRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/news-feed': typeof AuthenticatedNewsFeedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/phone': typeof AuthenticatedPhoneRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/post-deal': typeof AuthenticatedPostDealRoute
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/sophai': typeof AuthenticatedSophaiRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/back-office/advanced-desk': typeof AuthenticatedBackOfficeAdvancedDeskRoute
  '/back-office/case-design': typeof AuthenticatedBackOfficeCaseDesignRoute
  '/back-office/client-marketing': typeof AuthenticatedBackOfficeClientMarketingRoute
  '/back-office/recruiting-funnels': typeof AuthenticatedBackOfficeRecruitingFunnelsRoute
  '/back-office/recruiting-tracker': typeof AuthenticatedBackOfficeRecruitingTrackerRoute
  '/contracting/annuity-training': typeof AuthenticatedContractingAnnuityTrainingRoute
  '/contracting/carriers': typeof AuthenticatedContractingCarriersRoute
  '/contracting/commission-grids': typeof AuthenticatedContractingCommissionGridsRoute
  '/contracting/invite': typeof AuthenticatedContractingInviteRoute
  '/contracting/transfers': typeof AuthenticatedContractingTransfersRoute
  '/resources/agent-academy': typeof AuthenticatedResourcesAgentAcademyRoute
  '/resources/agent-handbook': typeof AuthenticatedResourcesAgentHandbookRoute
  '/resources/new-agent-guide': typeof AuthenticatedResourcesNewAgentGuideRoute
  '/resources/scripts': typeof AuthenticatedResourcesScriptsRoute
  '/resources/state-licenses': typeof AuthenticatedResourcesStateLicensesRoute
  '/sophai/activity': typeof AuthenticatedSophaiActivityRoute
  '/sophai/settings': typeof AuthenticatedSophaiSettingsRoute
  '/contracting': typeof AuthenticatedContractingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/back-office': typeof AuthenticatedBackOfficeRouteWithChildren
  '/_authenticated/book-of-business': typeof AuthenticatedBookOfBusinessRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/contracting': typeof AuthenticatedContractingRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/news-feed': typeof AuthenticatedNewsFeedRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/phone': typeof AuthenticatedPhoneRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/post-deal': typeof AuthenticatedPostDealRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/_authenticated/sophai': typeof AuthenticatedSophaiRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/back-office/advanced-desk': typeof AuthenticatedBackOfficeAdvancedDeskRoute
  '/_authenticated/back-office/case-design': typeof AuthenticatedBackOfficeCaseDesignRoute
  '/_authenticated/back-office/client-marketing': typeof AuthenticatedBackOfficeClientMarketingRoute
  '/_authenticated/back-office/recruiting-funnels': typeof AuthenticatedBackOfficeRecruitingFunnelsRoute
  '/_authenticated/back-office/recruiting-tracker': typeof AuthenticatedBackOfficeRecruitingTrackerRoute
  '/_authenticated/contracting/annuity-training': typeof AuthenticatedContractingAnnuityTrainingRoute
  '/_authenticated/contracting/carriers': typeof AuthenticatedContractingCarriersRoute
  '/_authenticated/contracting/commission-grids': typeof AuthenticatedContractingCommissionGridsRoute
  '/_authenticated/contracting/invite': typeof AuthenticatedContractingInviteRoute
  '/_authenticated/contracting/transfers': typeof AuthenticatedContractingTransfersRoute
  '/_authenticated/resources/agent-academy': typeof AuthenticatedResourcesAgentAcademyRoute
  '/_authenticated/resources/agent-handbook': typeof AuthenticatedResourcesAgentHandbookRoute
  '/_authenticated/resources/new-agent-guide': typeof AuthenticatedResourcesNewAgentGuideRoute
  '/_authenticated/resources/scripts': typeof AuthenticatedResourcesScriptsRoute
  '/_authenticated/resources/state-licenses': typeof AuthenticatedResourcesStateLicensesRoute
  '/_authenticated/sophai/activity': typeof AuthenticatedSophaiActivityRoute
  '/_authenticated/sophai/settings': typeof AuthenticatedSophaiSettingsRoute
  '/_authenticated/contracting/': typeof AuthenticatedContractingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ai-assistant'
    | '/analytics'
    | '/announcements'
    | '/back-office'
    | '/book-of-business'
    | '/calendar'
    | '/challenges'
    | '/contracting'
    | '/dashboard'
    | '/finances'
    | '/news-feed'
    | '/notifications'
    | '/phone'
    | '/pipeline'
    | '/post-deal'
    | '/resources'
    | '/sophai'
    | '/team'
    | '/back-office/advanced-desk'
    | '/back-office/case-design'
    | '/back-office/client-marketing'
    | '/back-office/recruiting-funnels'
    | '/back-office/recruiting-tracker'
    | '/contracting/annuity-training'
    | '/contracting/carriers'
    | '/contracting/commission-grids'
    | '/contracting/invite'
    | '/contracting/transfers'
    | '/resources/agent-academy'
    | '/resources/agent-handbook'
    | '/resources/new-agent-guide'
    | '/resources/scripts'
    | '/resources/state-licenses'
    | '/sophai/activity'
    | '/sophai/settings'
    | '/contracting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ai-assistant'
    | '/analytics'
    | '/announcements'
    | '/back-office'
    | '/book-of-business'
    | '/calendar'
    | '/challenges'
    | '/dashboard'
    | '/finances'
    | '/news-feed'
    | '/notifications'
    | '/phone'
    | '/pipeline'
    | '/post-deal'
    | '/resources'
    | '/sophai'
    | '/team'
    | '/back-office/advanced-desk'
    | '/back-office/case-design'
    | '/back-office/client-marketing'
    | '/back-office/recruiting-funnels'
    | '/back-office/recruiting-tracker'
    | '/contracting/annuity-training'
    | '/contracting/carriers'
    | '/contracting/commission-grids'
    | '/contracting/invite'
    | '/contracting/transfers'
    | '/resources/agent-academy'
    | '/resources/agent-handbook'
    | '/resources/new-agent-guide'
    | '/resources/scripts'
    | '/resources/state-licenses'
    | '/sophai/activity'
    | '/sophai/settings'
    | '/contracting'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/analytics'
    | '/_authenticated/announcements'
    | '/_authenticated/back-office'
    | '/_authenticated/book-of-business'
    | '/_authenticated/calendar'
    | '/_authenticated/challenges'
    | '/_authenticated/contracting'
    | '/_authenticated/dashboard'
    | '/_authenticated/finances'
    | '/_authenticated/news-feed'
    | '/_authenticated/notifications'
    | '/_authenticated/phone'
    | '/_authenticated/pipeline'
    | '/_authenticated/post-deal'
    | '/_authenticated/resources'
    | '/_authenticated/sophai'
    | '/_authenticated/team'
    | '/_authenticated/back-office/advanced-desk'
    | '/_authenticated/back-office/case-design'
    | '/_authenticated/back-office/client-marketing'
    | '/_authenticated/back-office/recruiting-funnels'
    | '/_authenticated/back-office/recruiting-tracker'
    | '/_authenticated/contracting/annuity-training'
    | '/_authenticated/contracting/carriers'
    | '/_authenticated/contracting/commission-grids'
    | '/_authenticated/contracting/invite'
    | '/_authenticated/contracting/transfers'
    | '/_authenticated/resources/agent-academy'
    | '/_authenticated/resources/agent-handbook'
    | '/_authenticated/resources/new-agent-guide'
    | '/_authenticated/resources/scripts'
    | '/_authenticated/resources/state-licenses'
    | '/_authenticated/sophai/activity'
    | '/_authenticated/sophai/settings'
    | '/_authenticated/contracting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sophai': {
      id: '/_authenticated/sophai'
      path: '/sophai'
      fullPath: '/sophai'
      preLoaderRoute: typeof AuthenticatedSophaiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/post-deal': {
      id: '/_authenticated/post-deal'
      path: '/post-deal'
      fullPath: '/post-deal'
      preLoaderRoute: typeof AuthenticatedPostDealRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phone': {
      id: '/_authenticated/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof AuthenticatedPhoneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/news-feed': {
      id: '/_authenticated/news-feed'
      path: '/news-feed'
      fullPath: '/news-feed'
      preLoaderRoute: typeof AuthenticatedNewsFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracting': {
      id: '/_authenticated/contracting'
      path: '/contracting'
      fullPath: '/contracting'
      preLoaderRoute: typeof AuthenticatedContractingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/book-of-business': {
      id: '/_authenticated/book-of-business'
      path: '/book-of-business'
      fullPath: '/book-of-business'
      preLoaderRoute: typeof AuthenticatedBookOfBusinessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/back-office': {
      id: '/_authenticated/back-office'
      path: '/back-office'
      fullPath: '/back-office'
      preLoaderRoute: typeof AuthenticatedBackOfficeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracting/': {
      id: '/_authenticated/contracting/'
      path: '/'
      fullPath: '/contracting/'
      preLoaderRoute: typeof AuthenticatedContractingIndexRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/sophai/settings': {
      id: '/_authenticated/sophai/settings'
      path: '/settings'
      fullPath: '/sophai/settings'
      preLoaderRoute: typeof AuthenticatedSophaiSettingsRouteImport
      parentRoute: typeof AuthenticatedSophaiRoute
    }
    '/_authenticated/sophai/activity': {
      id: '/_authenticated/sophai/activity'
      path: '/activity'
      fullPath: '/sophai/activity'
      preLoaderRoute: typeof AuthenticatedSophaiActivityRouteImport
      parentRoute: typeof AuthenticatedSophaiRoute
    }
    '/_authenticated/resources/state-licenses': {
      id: '/_authenticated/resources/state-licenses'
      path: '/state-licenses'
      fullPath: '/resources/state-licenses'
      preLoaderRoute: typeof AuthenticatedResourcesStateLicensesRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/resources/scripts': {
      id: '/_authenticated/resources/scripts'
      path: '/scripts'
      fullPath: '/resources/scripts'
      preLoaderRoute: typeof AuthenticatedResourcesScriptsRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/resources/new-agent-guide': {
      id: '/_authenticated/resources/new-agent-guide'
      path: '/new-agent-guide'
      fullPath: '/resources/new-agent-guide'
      preLoaderRoute: typeof AuthenticatedResourcesNewAgentGuideRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/resources/agent-handbook': {
      id: '/_authenticated/resources/agent-handbook'
      path: '/agent-handbook'
      fullPath: '/resources/agent-handbook'
      preLoaderRoute: typeof AuthenticatedResourcesAgentHandbookRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/resources/agent-academy': {
      id: '/_authenticated/resources/agent-academy'
      path: '/agent-academy'
      fullPath: '/resources/agent-academy'
      preLoaderRoute: typeof AuthenticatedResourcesAgentAcademyRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/contracting/transfers': {
      id: '/_authenticated/contracting/transfers'
      path: '/transfers'
      fullPath: '/contracting/transfers'
      preLoaderRoute: typeof AuthenticatedContractingTransfersRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/contracting/invite': {
      id: '/_authenticated/contracting/invite'
      path: '/invite'
      fullPath: '/contracting/invite'
      preLoaderRoute: typeof AuthenticatedContractingInviteRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/contracting/commission-grids': {
      id: '/_authenticated/contracting/commission-grids'
      path: '/commission-grids'
      fullPath: '/contracting/commission-grids'
      preLoaderRoute: typeof AuthenticatedContractingCommissionGridsRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/contracting/carriers': {
      id: '/_authenticated/contracting/carriers'
      path: '/carriers'
      fullPath: '/contracting/carriers'
      preLoaderRoute: typeof AuthenticatedContractingCarriersRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/contracting/annuity-training': {
      id: '/_authenticated/contracting/annuity-training'
      path: '/annuity-training'
      fullPath: '/contracting/annuity-training'
      preLoaderRoute: typeof AuthenticatedContractingAnnuityTrainingRouteImport
      parentRoute: typeof AuthenticatedContractingRoute
    }
    '/_authenticated/back-office/recruiting-tracker': {
      id: '/_authenticated/back-office/recruiting-tracker'
      path: '/recruiting-tracker'
      fullPath: '/back-office/recruiting-tracker'
      preLoaderRoute: typeof AuthenticatedBackOfficeRecruitingTrackerRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
    '/_authenticated/back-office/recruiting-funnels': {
      id: '/_authenticated/back-office/recruiting-funnels'
      path: '/recruiting-funnels'
      fullPath: '/back-office/recruiting-funnels'
      preLoaderRoute: typeof AuthenticatedBackOfficeRecruitingFunnelsRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
    '/_authenticated/back-office/client-marketing': {
      id: '/_authenticated/back-office/client-marketing'
      path: '/client-marketing'
      fullPath: '/back-office/client-marketing'
      preLoaderRoute: typeof AuthenticatedBackOfficeClientMarketingRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
    '/_authenticated/back-office/case-design': {
      id: '/_authenticated/back-office/case-design'
      path: '/case-design'
      fullPath: '/back-office/case-design'
      preLoaderRoute: typeof AuthenticatedBackOfficeCaseDesignRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
    '/_authenticated/back-office/advanced-desk': {
      id: '/_authenticated/back-office/advanced-desk'
      path: '/advanced-desk'
      fullPath: '/back-office/advanced-desk'
      preLoaderRoute: typeof AuthenticatedBackOfficeAdvancedDeskRouteImport
      parentRoute: typeof AuthenticatedBackOfficeRoute
    }
  }
}

interface AuthenticatedBackOfficeRouteChildren {
  AuthenticatedBackOfficeAdvancedDeskRoute: typeof AuthenticatedBackOfficeAdvancedDeskRoute
  AuthenticatedBackOfficeCaseDesignRoute: typeof AuthenticatedBackOfficeCaseDesignRoute
  AuthenticatedBackOfficeClientMarketingRoute: typeof AuthenticatedBackOfficeClientMarketingRoute
  AuthenticatedBackOfficeRecruitingFunnelsRoute: typeof AuthenticatedBackOfficeRecruitingFunnelsRoute
  AuthenticatedBackOfficeRecruitingTrackerRoute: typeof AuthenticatedBackOfficeRecruitingTrackerRoute
}

const AuthenticatedBackOfficeRouteChildren: AuthenticatedBackOfficeRouteChildren =
  {
    AuthenticatedBackOfficeAdvancedDeskRoute:
      AuthenticatedBackOfficeAdvancedDeskRoute,
    AuthenticatedBackOfficeCaseDesignRoute:
      AuthenticatedBackOfficeCaseDesignRoute,
    AuthenticatedBackOfficeClientMarketingRoute:
      AuthenticatedBackOfficeClientMarketingRoute,
    AuthenticatedBackOfficeRecruitingFunnelsRoute:
      AuthenticatedBackOfficeRecruitingFunnelsRoute,
    AuthenticatedBackOfficeRecruitingTrackerRoute:
      AuthenticatedBackOfficeRecruitingTrackerRoute,
  }

const AuthenticatedBackOfficeRouteWithChildren =
  AuthenticatedBackOfficeRoute._addFileChildren(
    AuthenticatedBackOfficeRouteChildren,
  )

interface AuthenticatedContractingRouteChildren {
  AuthenticatedContractingAnnuityTrainingRoute: typeof AuthenticatedContractingAnnuityTrainingRoute
  AuthenticatedContractingCarriersRoute: typeof AuthenticatedContractingCarriersRoute
  AuthenticatedContractingCommissionGridsRoute: typeof AuthenticatedContractingCommissionGridsRoute
  AuthenticatedContractingInviteRoute: typeof AuthenticatedContractingInviteRoute
  AuthenticatedContractingTransfersRoute: typeof AuthenticatedContractingTransfersRoute
  AuthenticatedContractingIndexRoute: typeof AuthenticatedContractingIndexRoute
}

const AuthenticatedContractingRouteChildren: AuthenticatedContractingRouteChildren =
  {
    AuthenticatedContractingAnnuityTrainingRoute:
      AuthenticatedContractingAnnuityTrainingRoute,
    AuthenticatedContractingCarriersRoute:
      AuthenticatedContractingCarriersRoute,
    AuthenticatedContractingCommissionGridsRoute:
      AuthenticatedContractingCommissionGridsRoute,
    AuthenticatedContractingInviteRoute: AuthenticatedContractingInviteRoute,
    AuthenticatedContractingTransfersRoute:
      AuthenticatedContractingTransfersRoute,
    AuthenticatedContractingIndexRoute: AuthenticatedContractingIndexRoute,
  }

const AuthenticatedContractingRouteWithChildren =
  AuthenticatedContractingRoute._addFileChildren(
    AuthenticatedContractingRouteChildren,
  )

interface AuthenticatedResourcesRouteChildren {
  AuthenticatedResourcesAgentAcademyRoute: typeof AuthenticatedResourcesAgentAcademyRoute
  AuthenticatedResourcesAgentHandbookRoute: typeof AuthenticatedResourcesAgentHandbookRoute
  AuthenticatedResourcesNewAgentGuideRoute: typeof AuthenticatedResourcesNewAgentGuideRoute
  AuthenticatedResourcesScriptsRoute: typeof AuthenticatedResourcesScriptsRoute
  AuthenticatedResourcesStateLicensesRoute: typeof AuthenticatedResourcesStateLicensesRoute
}

const AuthenticatedResourcesRouteChildren: AuthenticatedResourcesRouteChildren =
  {
    AuthenticatedResourcesAgentAcademyRoute:
      AuthenticatedResourcesAgentAcademyRoute,
    AuthenticatedResourcesAgentHandbookRoute:
      AuthenticatedResourcesAgentHandbookRoute,
    AuthenticatedResourcesNewAgentGuideRoute:
      AuthenticatedResourcesNewAgentGuideRoute,
    AuthenticatedResourcesScriptsRoute: AuthenticatedResourcesScriptsRoute,
    AuthenticatedResourcesStateLicensesRoute:
      AuthenticatedResourcesStateLicensesRoute,
  }

const AuthenticatedResourcesRouteWithChildren =
  AuthenticatedResourcesRoute._addFileChildren(
    AuthenticatedResourcesRouteChildren,
  )

interface AuthenticatedSophaiRouteChildren {
  AuthenticatedSophaiActivityRoute: typeof AuthenticatedSophaiActivityRoute
  AuthenticatedSophaiSettingsRoute: typeof AuthenticatedSophaiSettingsRoute
}

const AuthenticatedSophaiRouteChildren: AuthenticatedSophaiRouteChildren = {
  AuthenticatedSophaiActivityRoute: AuthenticatedSophaiActivityRoute,
  AuthenticatedSophaiSettingsRoute: AuthenticatedSophaiSettingsRoute,
}

const AuthenticatedSophaiRouteWithChildren =
  AuthenticatedSophaiRoute._addFileChildren(AuthenticatedSophaiRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedBackOfficeRoute: typeof AuthenticatedBackOfficeRouteWithChildren
  AuthenticatedBookOfBusinessRoute: typeof AuthenticatedBookOfBusinessRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedContractingRoute: typeof AuthenticatedContractingRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedNewsFeedRoute: typeof AuthenticatedNewsFeedRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPhoneRoute: typeof AuthenticatedPhoneRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPostDealRoute: typeof AuthenticatedPostDealRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRouteWithChildren
  AuthenticatedSophaiRoute: typeof AuthenticatedSophaiRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedBackOfficeRoute: AuthenticatedBackOfficeRouteWithChildren,
  AuthenticatedBookOfBusinessRoute: AuthenticatedBookOfBusinessRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedContractingRoute: AuthenticatedContractingRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedNewsFeedRoute: AuthenticatedNewsFeedRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPhoneRoute: AuthenticatedPhoneRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPostDealRoute: AuthenticatedPostDealRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRouteWithChildren,
  AuthenticatedSophaiRoute: AuthenticatedSophaiRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
