-- 1. Add UNIQUE constraint on carriers.name (idempotent)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.carriers'::regclass
      AND contype = 'u'
      AND conname = 'carriers_name_unique'
  ) THEN
    ALTER TABLE public.carriers ADD CONSTRAINT carriers_name_unique UNIQUE (name);
  END IF;
END $$;

-- 2. Upsert the 10 carriers
INSERT INTO public.carriers (name, active) VALUES
  ('Guarantee Trust Life', true),
  ('Transamerica', true),
  ('American Home Life', true),
  ('American Amicable', true),
  ('Mutual of Omaha', true),
  ('Foresters', true),
  ('Prudential', true),
  ('Baltimore Life', true),
  ('Newbridge', true),
  ('Royal Neighbors', true)
ON CONFLICT (name) DO UPDATE SET active = true;

-- 3. Delete existing grid rows for these carriers
DELETE FROM public.commission_grids
WHERE carrier_id IN (
  SELECT id FROM public.carriers
  WHERE name IN (
    'Guarantee Trust Life','Transamerica','American Home Life','American Amicable',
    'Mutual of Omaha','Foresters','Prudential','Baltimore Life','Newbridge','Royal Neighbors'
  )
);

-- 4. Insert all product × level rows
WITH carriers_map AS (
  SELECT id, name FROM public.carriers
  WHERE name IN (
    'Guarantee Trust Life','Transamerica','American Home Life','American Amicable',
    'Mutual of Omaha','Foresters','Prudential','Baltimore Life','Newbridge','Royal Neighbors'
  )
),
grid_data(carrier_name, product_name, age_min, age_max, y1, y25, y6, lvl) AS (VALUES
  ('Guarantee Trust Life'::text,'Heritage'::text,NULL::int,NULL::int,80::numeric,5::numeric,NULL::numeric,'30 (80%)'::text),
  ('Guarantee Trust Life','Heritage',NULL,NULL,75,4.5,NULL,'S+3'),
  ('Guarantee Trust Life','Heritage',NULL,NULL,70,4.5,NULL,'S+2'),
  ('Guarantee Trust Life','Heritage',NULL,NULL,65,4,NULL,'S+1'),
  ('Guarantee Trust Life','Heritage',NULL,NULL,60,4,NULL,'22 (60%)'),
  ('Guarantee Trust Life','Heritage',NULL,NULL,55,3.5,NULL,'20 (55%)'),
  ('Guarantee Trust Life','Heritage',NULL,NULL,50,3,NULL,'18 (50%)'),
  ('Guarantee Trust Life','Life Select',NULL,NULL,80,5,NULL,'30 (80%)'),
  ('Guarantee Trust Life','Life Select',NULL,NULL,75,4.5,NULL,'S+3'),
  ('Guarantee Trust Life','Life Select',NULL,NULL,70,4.5,NULL,'S+2'),
  ('Guarantee Trust Life','Life Select',NULL,NULL,65,4,NULL,'S+1'),
  ('Guarantee Trust Life','Life Select',NULL,NULL,60,4,NULL,'22 (60%)'),
  ('Guarantee Trust Life','Life Select',NULL,NULL,55,3.5,NULL,'20 (55%)'),
  ('Guarantee Trust Life','Life Select',NULL,NULL,50,3,NULL,'18 (50%)'),
  ('Transamerica','Immediate Solution',NULL,NULL,122,NULL,NULL,'RK20'),
  ('Transamerica','Immediate Solution',NULL,NULL,65,NULL,NULL,'RK12'),
  ('Transamerica','Immediate Solution',NULL,NULL,61,NULL,NULL,'RK11'),
  ('Transamerica','Immediate Solution',NULL,NULL,57,NULL,NULL,'RK10'),
  ('Transamerica','Immediate Solution',NULL,NULL,53,NULL,NULL,'RK8'),
  ('Transamerica','Immediate Solution',NULL,NULL,NULL,NULL,NULL,'RK9 (LOA)'),
  ('Transamerica','FE Express',NULL,NULL,150,NULL,NULL,'RK20'),
  ('Transamerica','FE Express',NULL,NULL,80,NULL,NULL,'RK12'),
  ('Transamerica','FE Express',NULL,NULL,75,NULL,NULL,'RK11'),
  ('Transamerica','FE Express',NULL,NULL,70,NULL,NULL,'RK10'),
  ('Transamerica','FE Express',NULL,NULL,65,NULL,NULL,'RK8'),
  ('Transamerica','FE Express',NULL,NULL,NULL,NULL,NULL,'RK9 (LOA)'),
  ('Transamerica','Whole Life',NULL,NULL,131,NULL,NULL,'RK20'),
  ('Transamerica','Whole Life',NULL,NULL,70,NULL,NULL,'RK12'),
  ('Transamerica','Whole Life',NULL,NULL,65.5,NULL,NULL,'RK11'),
  ('Transamerica','Whole Life',NULL,NULL,61,NULL,NULL,'RK10'),
  ('Transamerica','Whole Life',NULL,NULL,57,NULL,NULL,'RK8'),
  ('Transamerica','Whole Life',NULL,NULL,NULL,NULL,NULL,'RK9 (LOA)'),
  ('Transamerica','Trendsetter Super 10 Year',NULL,NULL,84.5,NULL,NULL,'RK20'),
  ('Transamerica','Trendsetter Super 10 Year',NULL,NULL,45,NULL,NULL,'RK12'),
  ('Transamerica','Trendsetter Super 10 Year',NULL,NULL,42,NULL,NULL,'RK11'),
  ('Transamerica','Trendsetter Super 10 Year',NULL,NULL,39.5,NULL,NULL,'RK10'),
  ('Transamerica','Trendsetter Super 10 Year',NULL,NULL,36.5,NULL,NULL,'RK8'),
  ('Transamerica','Trendsetter Super 10 Year',NULL,NULL,NULL,NULL,NULL,'RK9 (LOA)'),
  ('Transamerica','Trendsetter Super 15 Year',NULL,NULL,94,NULL,NULL,'RK20'),
  ('Transamerica','Trendsetter Super 15 Year',NULL,NULL,50,NULL,NULL,'RK12'),
  ('Transamerica','Trendsetter Super 15 Year',NULL,NULL,47,NULL,NULL,'RK11'),
  ('Transamerica','Trendsetter Super 15 Year',NULL,NULL,44,NULL,NULL,'RK10'),
  ('Transamerica','Trendsetter Super 15 Year',NULL,NULL,40.5,NULL,NULL,'RK8'),
  ('Transamerica','Trendsetter Super 15 Year',NULL,NULL,NULL,NULL,NULL,'RK9 (LOA)'),
  ('Transamerica','Trendsetter Super 20/25/30 Year',NULL,NULL,103,NULL,NULL,'RK20'),
  ('Transamerica','Trendsetter Super 20/25/30 Year',NULL,NULL,55,NULL,NULL,'RK12'),
  ('Transamerica','Trendsetter Super 20/25/30 Year',NULL,NULL,51.5,NULL,NULL,'RK11'),
  ('Transamerica','Trendsetter Super 20/25/30 Year',NULL,NULL,48,NULL,NULL,'RK10'),
  ('Transamerica','Trendsetter Super 20/25/30 Year',NULL,NULL,44.5,NULL,NULL,'RK8'),
  ('Transamerica','Trendsetter Super 20/25/30 Year',NULL,NULL,NULL,NULL,NULL,'RK9 (LOA)'),
  ('Transamerica','Trendsetter LB 10 Year',NULL,NULL,75,NULL,NULL,'RK20'),
  ('Transamerica','Trendsetter LB 10 Year',NULL,NULL,40,NULL,NULL,'RK12'),
  ('Transamerica','Trendsetter LB 10 Year',NULL,NULL,37.5,NULL,NULL,'RK11'),
  ('Transamerica','Trendsetter LB 10 Year',NULL,NULL,35,NULL,NULL,'RK10'),
  ('Transamerica','Trendsetter LB 10 Year',NULL,NULL,32.5,NULL,NULL,'RK8'),
  ('Transamerica','Trendsetter LB 10 Year',NULL,NULL,NULL,NULL,NULL,'RK9 (LOA)'),
  ('Transamerica','Trendsetter LB 15 Year',NULL,NULL,103,NULL,NULL,'RK20'),
  ('Transamerica','Trendsetter LB 15 Year',NULL,NULL,55,NULL,NULL,'RK12'),
  ('Transamerica','Trendsetter LB 15 Year',NULL,NULL,51.5,NULL,NULL,'RK11'),
  ('Transamerica','Trendsetter LB 15 Year',NULL,NULL,48,NULL,NULL,'RK10'),
  ('Transamerica','Trendsetter LB 15 Year',NULL,NULL,44.5,NULL,NULL,'RK8'),
  ('Transamerica','Trendsetter LB 15 Year',NULL,NULL,NULL,NULL,NULL,'RK9 (LOA)'),
  ('Transamerica','Trendsetter LB 20/25/30 Year',NULL,NULL,122,NULL,NULL,'RK20'),
  ('Transamerica','Trendsetter LB 20/25/30 Year',NULL,NULL,65,NULL,NULL,'RK12'),
  ('Transamerica','Trendsetter LB 20/25/30 Year',NULL,NULL,61,NULL,NULL,'RK11'),
  ('Transamerica','Trendsetter LB 20/25/30 Year',NULL,NULL,57,NULL,NULL,'RK10'),
  ('Transamerica','Trendsetter LB 20/25/30 Year',NULL,NULL,53,NULL,NULL,'RK8'),
  ('Transamerica','Trendsetter LB 20/25/30 Year',NULL,NULL,NULL,NULL,NULL,'RK9 (LOA)'),
  ('American Home Life','Final Expense',NULL,NULL,150,NULL,NULL,'GA (24)'),
  ('American Home Life','Final Expense',NULL,NULL,80,NULL,NULL,'GA (10)'),
  ('American Home Life','Final Expense',NULL,NULL,75,NULL,NULL,'GA (9)'),
  ('American Home Life','Final Expense',NULL,NULL,70,NULL,NULL,'GA (8)'),
  ('American Home Life','Final Expense',NULL,NULL,65,NULL,NULL,'GA (7)'),
  ('American Home Life','Final Expense',NULL,NULL,60,NULL,NULL,'GA (6)'),
  ('American Home Life','Final Expense',NULL,NULL,55,NULL,NULL,'GA (5)'),
  ('American Home Life','Final Expense',NULL,NULL,50,NULL,NULL,'GA (4)'),
  ('American Home Life','Final Expense',NULL,NULL,45,NULL,NULL,'GA (3)'),
  ('American Home Life','Final Expense',NULL,NULL,40,NULL,NULL,'GA (2)'),
  ('American Amicable','Senior Choice FE',NULL,NULL,150,NULL,NULL,'150'),
  ('American Amicable','Senior Choice FE',NULL,NULL,75,NULL,NULL,'75'),
  ('American Amicable','Senior Choice FE',NULL,NULL,70,NULL,NULL,'70'),
  ('American Amicable','Senior Choice FE',NULL,NULL,65,NULL,NULL,'65'),
  ('American Amicable','Senior Choice FE',NULL,NULL,60,NULL,NULL,'60'),
  ('American Amicable','Senior Choice FE',NULL,NULL,55,NULL,NULL,'55'),
  ('American Amicable','Senior Choice FE',NULL,NULL,50,NULL,NULL,'50'),
  ('American Amicable','Senior Choice FE',NULL,NULL,45,NULL,NULL,'45'),
  ('American Amicable','Senior Choice FE',NULL,NULL,40,NULL,NULL,'40'),
  ('American Amicable','Easy Term 20-30yr',NULL,NULL,120,NULL,NULL,'150'),
  ('American Amicable','Easy Term 20-30yr',NULL,NULL,60,NULL,NULL,'75'),
  ('American Amicable','Easy Term 20-30yr',NULL,NULL,56,NULL,NULL,'70'),
  ('American Amicable','Easy Term 20-30yr',NULL,NULL,52,NULL,NULL,'65'),
  ('American Amicable','Easy Term 20-30yr',NULL,NULL,48,NULL,NULL,'60'),
  ('American Amicable','Easy Term 20-30yr',NULL,NULL,44,NULL,NULL,'55'),
  ('American Amicable','Easy Term 20-30yr',NULL,NULL,40,NULL,NULL,'50'),
  ('American Amicable','Easy Term 20-30yr',NULL,NULL,36,NULL,NULL,'45'),
  ('American Amicable','Easy Term 20-30yr',NULL,NULL,32,NULL,NULL,'40'),
  ('American Amicable','Express UL',NULL,NULL,110,NULL,NULL,'150'),
  ('American Amicable','Express UL',NULL,NULL,55,NULL,NULL,'75'),
  ('American Amicable','Express UL',NULL,NULL,51.5,NULL,NULL,'70'),
  ('American Amicable','Express UL',NULL,NULL,47.5,NULL,NULL,'65'),
  ('American Amicable','Express UL',NULL,NULL,44,NULL,NULL,'60'),
  ('American Amicable','Express UL',NULL,NULL,40.5,NULL,NULL,'55'),
  ('American Amicable','Express UL',NULL,NULL,36.5,NULL,NULL,'50'),
  ('American Amicable','Express UL',NULL,NULL,33,NULL,NULL,'45'),
  ('American Amicable','Express UL',NULL,NULL,29.5,NULL,NULL,'40'),
  ('American Amicable','Home Protector',NULL,NULL,170,NULL,NULL,'150'),
  ('American Amicable','Home Protector',NULL,NULL,85,NULL,NULL,'75'),
  ('American Amicable','Home Protector',NULL,NULL,79.5,NULL,NULL,'70'),
  ('American Amicable','Home Protector',NULL,NULL,73.5,NULL,NULL,'65'),
  ('American Amicable','Home Protector',NULL,NULL,68,NULL,NULL,'60'),
  ('American Amicable','Home Protector',NULL,NULL,62.5,NULL,NULL,'55'),
  ('American Amicable','Home Protector',NULL,NULL,56.5,NULL,NULL,'50'),
  ('American Amicable','Home Protector',NULL,NULL,51,NULL,NULL,'45'),
  ('American Amicable','Home Protector',NULL,NULL,45.5,NULL,NULL,'40'),
  ('American Amicable','Secure Life Plus',NULL,NULL,190,NULL,NULL,'150'),
  ('American Amicable','Secure Life Plus',NULL,NULL,95,NULL,NULL,'75'),
  ('American Amicable','Secure Life Plus',NULL,NULL,88.5,NULL,NULL,'70'),
  ('American Amicable','Secure Life Plus',NULL,NULL,82.5,NULL,NULL,'65'),
  ('American Amicable','Secure Life Plus',NULL,NULL,76,NULL,NULL,'60'),
  ('American Amicable','Secure Life Plus',NULL,NULL,69.5,NULL,NULL,'55'),
  ('American Amicable','Secure Life Plus',NULL,NULL,63.5,NULL,NULL,'50'),
  ('American Amicable','Secure Life Plus',NULL,NULL,57,NULL,NULL,'45'),
  ('American Amicable','Secure Life Plus',NULL,NULL,50.5,NULL,NULL,'40'),
  ('American Amicable','Term Made Simple',NULL,NULL,110,NULL,NULL,'150'),
  ('American Amicable','Term Made Simple',NULL,NULL,55,NULL,NULL,'75'),
  ('American Amicable','Term Made Simple',NULL,NULL,51.5,NULL,NULL,'70'),
  ('American Amicable','Term Made Simple',NULL,NULL,47.5,NULL,NULL,'65'),
  ('American Amicable','Term Made Simple',NULL,NULL,44,NULL,NULL,'60'),
  ('American Amicable','Term Made Simple',NULL,NULL,40.5,NULL,NULL,'55'),
  ('American Amicable','Term Made Simple',NULL,NULL,36.5,NULL,NULL,'50'),
  ('American Amicable','Term Made Simple',NULL,NULL,33,NULL,NULL,'45'),
  ('American Amicable','Term Made Simple',NULL,NULL,29.5,NULL,NULL,'40'),
  ('American Amicable','Security Protector',NULL,NULL,120,NULL,NULL,'150'),
  ('American Amicable','Security Protector',NULL,NULL,60,NULL,NULL,'75'),
  ('American Amicable','Security Protector',NULL,NULL,56,NULL,NULL,'70'),
  ('American Amicable','Security Protector',NULL,NULL,52,NULL,NULL,'65'),
  ('American Amicable','Security Protector',NULL,NULL,48,NULL,NULL,'60'),
  ('American Amicable','Security Protector',NULL,NULL,44,NULL,NULL,'55'),
  ('American Amicable','Security Protector',NULL,NULL,40,NULL,NULL,'50'),
  ('American Amicable','Security Protector',NULL,NULL,36,NULL,NULL,'45'),
  ('American Amicable','Security Protector',NULL,NULL,32,NULL,NULL,'40'),
  ('American Amicable','Survivor Protector',NULL,NULL,180,NULL,NULL,'150'),
  ('American Amicable','Survivor Protector',NULL,NULL,90,NULL,NULL,'75'),
  ('American Amicable','Survivor Protector',NULL,NULL,84,NULL,NULL,'70'),
  ('American Amicable','Survivor Protector',NULL,NULL,78,NULL,NULL,'65'),
  ('American Amicable','Survivor Protector',NULL,NULL,72,NULL,NULL,'60'),
  ('American Amicable','Survivor Protector',NULL,NULL,66,NULL,NULL,'55'),
  ('American Amicable','Survivor Protector',NULL,NULL,60,NULL,NULL,'50'),
  ('American Amicable','Survivor Protector',NULL,NULL,54,NULL,NULL,'45'),
  ('American Amicable','Survivor Protector',NULL,NULL,48,NULL,NULL,'40'),
  ('American Amicable','Platinum Solutions',NULL,NULL,160,NULL,NULL,'150'),
  ('American Amicable','Platinum Solutions',NULL,NULL,80,NULL,NULL,'75'),
  ('American Amicable','Platinum Solutions',NULL,NULL,74.5,NULL,NULL,'70'),
  ('American Amicable','Platinum Solutions',NULL,NULL,69.5,NULL,NULL,'65'),
  ('American Amicable','Platinum Solutions',NULL,NULL,64,NULL,NULL,'60'),
  ('American Amicable','Platinum Solutions',NULL,NULL,58.5,NULL,NULL,'55'),
  ('American Amicable','Platinum Solutions',NULL,NULL,53.5,NULL,NULL,'50'),
  ('American Amicable','Platinum Solutions',NULL,NULL,48,NULL,NULL,'45'),
  ('American Amicable','Platinum Solutions',NULL,NULL,42.5,NULL,NULL,'40'),
  ('American Amicable','Safe Care Term',NULL,NULL,190,NULL,NULL,'150'),
  ('American Amicable','Safe Care Term',NULL,NULL,95,NULL,NULL,'75'),
  ('American Amicable','Safe Care Term',NULL,NULL,88.5,NULL,NULL,'70'),
  ('American Amicable','Safe Care Term',NULL,NULL,82.5,NULL,NULL,'65'),
  ('American Amicable','Safe Care Term',NULL,NULL,76,NULL,NULL,'60'),
  ('American Amicable','Safe Care Term',NULL,NULL,69.5,NULL,NULL,'55'),
  ('American Amicable','Safe Care Term',NULL,NULL,63.5,NULL,NULL,'50'),
  ('American Amicable','Safe Care Term',NULL,NULL,57,NULL,NULL,'45'),
  ('American Amicable','Safe Care Term',NULL,NULL,50.5,NULL,NULL,'40'),
  ('American Amicable','Intelligent Choice',NULL,NULL,110,NULL,NULL,'150'),
  ('American Amicable','Intelligent Choice',NULL,NULL,55,NULL,NULL,'75'),
  ('American Amicable','Intelligent Choice',NULL,NULL,51.5,NULL,NULL,'70'),
  ('American Amicable','Intelligent Choice',NULL,NULL,47.5,NULL,NULL,'65'),
  ('American Amicable','Intelligent Choice',NULL,NULL,44,NULL,NULL,'60'),
  ('American Amicable','Intelligent Choice',NULL,NULL,40.5,NULL,NULL,'55'),
  ('American Amicable','Intelligent Choice',NULL,NULL,36.5,NULL,NULL,'50'),
  ('American Amicable','Intelligent Choice',NULL,NULL,33,NULL,NULL,'45'),
  ('American Amicable','Intelligent Choice',NULL,NULL,29.5,NULL,NULL,'40'),
  ('Mutual of Omaha','Living Promise Final Expense',NULL,NULL,150,NULL,NULL,'L1'),
  ('Mutual of Omaha','Living Promise Final Expense',NULL,NULL,74,NULL,NULL,'L15'),
  ('Mutual of Omaha','Living Promise Final Expense',NULL,NULL,70,NULL,NULL,'L16'),
  ('Mutual of Omaha','Living Promise Final Expense',NULL,NULL,65,NULL,NULL,'L17'),
  ('Mutual of Omaha','Living Promise Final Expense',NULL,NULL,61,NULL,NULL,'L18'),
  ('Mutual of Omaha','Living Promise Final Expense',NULL,NULL,57,NULL,NULL,'L19'),
  ('Mutual of Omaha','TLE',NULL,NULL,172.5,NULL,NULL,'L1'),
  ('Mutual of Omaha','TLE',NULL,NULL,85,NULL,NULL,'L15'),
  ('Mutual of Omaha','TLE',NULL,NULL,80.5,NULL,NULL,'L16'),
  ('Mutual of Omaha','TLE',NULL,NULL,74.5,NULL,NULL,'L17'),
  ('Mutual of Omaha','TLE',NULL,NULL,70,NULL,NULL,'L18'),
  ('Mutual of Omaha','TLE',NULL,NULL,65.5,NULL,NULL,'L19'),
  ('Mutual of Omaha','IULE',NULL,NULL,142,NULL,NULL,'L1'),
  ('Mutual of Omaha','IULE',NULL,NULL,70,NULL,NULL,'L15'),
  ('Mutual of Omaha','IULE',NULL,NULL,66,NULL,NULL,'L16'),
  ('Mutual of Omaha','IULE',NULL,NULL,61.5,NULL,NULL,'L17'),
  ('Mutual of Omaha','IULE',NULL,NULL,57.5,NULL,NULL,'L18'),
  ('Mutual of Omaha','IULE',NULL,NULL,54,NULL,NULL,'L19'),
  ('Mutual of Omaha','Whole Life',NULL,NULL,142,NULL,NULL,'L1'),
  ('Mutual of Omaha','Whole Life',NULL,NULL,70,NULL,NULL,'L15'),
  ('Mutual of Omaha','Whole Life',NULL,NULL,66,NULL,NULL,'L16'),
  ('Mutual of Omaha','Whole Life',NULL,NULL,61.5,NULL,NULL,'L17'),
  ('Mutual of Omaha','Whole Life',NULL,NULL,57.5,NULL,NULL,'L18'),
  ('Mutual of Omaha','Whole Life',NULL,NULL,54,NULL,NULL,'L19'),
  ('Mutual of Omaha','UL',NULL,NULL,101.5,NULL,NULL,'L1'),
  ('Mutual of Omaha','UL',NULL,NULL,50,NULL,NULL,'L15'),
  ('Mutual of Omaha','UL',NULL,NULL,47.5,NULL,NULL,'L16'),
  ('Mutual of Omaha','UL',NULL,NULL,44,NULL,NULL,'L17'),
  ('Mutual of Omaha','UL',NULL,NULL,41,NULL,NULL,'L18'),
  ('Mutual of Omaha','UL',NULL,NULL,38.5,NULL,NULL,'L19'),
  ('Mutual of Omaha','IUL',NULL,NULL,132,NULL,NULL,'L1'),
  ('Mutual of Omaha','IUL',NULL,NULL,65,NULL,NULL,'L15'),
  ('Mutual of Omaha','IUL',NULL,NULL,61.5,NULL,NULL,'L16'),
  ('Mutual of Omaha','IUL',NULL,NULL,57,NULL,NULL,'L17'),
  ('Mutual of Omaha','IUL',NULL,NULL,53.5,NULL,NULL,'L18'),
  ('Mutual of Omaha','IUL',NULL,NULL,50,NULL,NULL,'L19'),
  ('Mutual of Omaha','TLA 10 Year',NULL,NULL,77,NULL,NULL,'L1'),
  ('Mutual of Omaha','TLA 10 Year',NULL,NULL,38,NULL,NULL,'L15'),
  ('Mutual of Omaha','TLA 10 Year',NULL,NULL,36,NULL,NULL,'L16'),
  ('Mutual of Omaha','TLA 10 Year',NULL,NULL,33.5,NULL,NULL,'L17'),
  ('Mutual of Omaha','TLA 10 Year',NULL,NULL,31.5,NULL,NULL,'L18'),
  ('Mutual of Omaha','TLA 10 Year',NULL,NULL,29.5,NULL,NULL,'L19'),
  ('Mutual of Omaha','TLA 20/30 Year',NULL,NULL,121.5,NULL,NULL,'L1'),
  ('Mutual of Omaha','TLA 20/30 Year',NULL,NULL,60,NULL,NULL,'L15'),
  ('Mutual of Omaha','TLA 20/30 Year',NULL,NULL,57,NULL,NULL,'L16'),
  ('Mutual of Omaha','TLA 20/30 Year',NULL,NULL,52.5,NULL,NULL,'L17'),
  ('Mutual of Omaha','TLA 20/30 Year',NULL,NULL,49.5,NULL,NULL,'L18'),
  ('Mutual of Omaha','TLA 20/30 Year',NULL,NULL,46,NULL,NULL,'L19'),
  ('Foresters','PlanRight FE',50,80,150,11,7,'PKRAGENT20'),
  ('Foresters','PlanRight FE',50,80,80,6,4,'PKRAGENT10'),
  ('Foresters','PlanRight FE',50,80,75,5.5,3.5,'PKRAGENT9'),
  ('Foresters','PlanRight FE',50,80,70,5,3.5,'PKRAGENT7'),
  ('Foresters','PlanRight FE',50,80,65,4.5,3,'PKRAGENT5'),
  ('Foresters','PlanRight FE',50,80,60,4.5,3,'PKRAGENT3'),
  ('Foresters','PlanRight FE',50,80,55,4,2.5,'PKRAGT2A'),
  ('Foresters','PlanRight FE',50,80,50,3.5,2.5,'PKRAGT2B'),
  ('Foresters','PlanRight FE',50,80,45,3,2,'PKRAGT2C'),
  ('Foresters','PlanRight FE',50,80,NULL,NULL,NULL,'PKRAGENT1 (LOA)'),
  ('Foresters','PlanRight FE',81,85,97.5,11,7,'PKRAGENT20'),
  ('Foresters','PlanRight FE',81,85,52,6,4,'PKRAGENT10'),
  ('Foresters','PlanRight FE',81,85,49,5.5,3.5,'PKRAGENT9'),
  ('Foresters','PlanRight FE',81,85,45.5,5,3.5,'PKRAGENT7'),
  ('Foresters','PlanRight FE',81,85,42,4.5,3,'PKRAGENT5'),
  ('Foresters','PlanRight FE',81,85,39,4.5,3,'PKRAGENT3'),
  ('Foresters','PlanRight FE',81,85,36,4,2.5,'PKRAGT2A'),
  ('Foresters','PlanRight FE',81,85,32.5,3.5,2.5,'PKRAGT2B'),
  ('Foresters','PlanRight FE',81,85,29,3,2,'PKRAGT2C'),
  ('Foresters','PlanRight FE',81,85,NULL,NULL,NULL,'PKRAGENT1 (LOA)'),
  ('Foresters','PlanRight Modified Benefit WL',NULL,NULL,75,11,7,'PKRAGENT20'),
  ('Foresters','PlanRight Modified Benefit WL',NULL,NULL,40,6,4,'PKRAGENT10'),
  ('Foresters','PlanRight Modified Benefit WL',NULL,NULL,37.5,5.5,3.5,'PKRAGENT9'),
  ('Foresters','PlanRight Modified Benefit WL',NULL,NULL,35,5,3.5,'PKRAGENT7'),
  ('Foresters','PlanRight Modified Benefit WL',NULL,NULL,32.5,4.5,3,'PKRAGENT5'),
  ('Foresters','PlanRight Modified Benefit WL',NULL,NULL,30,4.5,3,'PKRAGENT3'),
  ('Foresters','PlanRight Modified Benefit WL',NULL,NULL,27.5,4,2.5,'PKRAGT2A'),
  ('Foresters','PlanRight Modified Benefit WL',NULL,NULL,25,3.5,2.5,'PKRAGT2B'),
  ('Foresters','PlanRight Modified Benefit WL',NULL,NULL,22.5,3,2,'PKRAGT2C'),
  ('Foresters','PlanRight Modified Benefit WL',NULL,NULL,NULL,NULL,NULL,'PKRAGENT1 (LOA)'),
  ('Foresters','Your Term Non-Med 15/20/25/30 Year',NULL,NULL,140.5,NULL,NULL,'PKRAGENT20'),
  ('Foresters','Your Term Non-Med 15/20/25/30 Year',NULL,NULL,75,NULL,NULL,'PKRAGENT10'),
  ('Foresters','Your Term Non-Med 15/20/25/30 Year',NULL,NULL,70.5,NULL,NULL,'PKRAGENT9'),
  ('Foresters','Your Term Non-Med 15/20/25/30 Year',NULL,NULL,65.5,NULL,NULL,'PKRAGENT7'),
  ('Foresters','Your Term Non-Med 15/20/25/30 Year',NULL,NULL,61,NULL,NULL,'PKRAGENT5'),
  ('Foresters','Your Term Non-Med 15/20/25/30 Year',NULL,NULL,56,NULL,NULL,'PKRAGENT3'),
  ('Foresters','Your Term Non-Med 15/20/25/30 Year',NULL,NULL,51.5,NULL,NULL,'PKRAGT2A'),
  ('Foresters','Your Term Non-Med 15/20/25/30 Year',NULL,NULL,47,NULL,NULL,'PKRAGT2B'),
  ('Foresters','Your Term Non-Med 15/20/25/30 Year',NULL,NULL,42,NULL,NULL,'PKRAGT2C'),
  ('Foresters','Your Term Non-Med 15/20/25/30 Year',NULL,NULL,NULL,NULL,NULL,'PKRAGENT1 (LOA)'),
  ('Foresters','Your Term Medical 15/20/25/30 Year',NULL,NULL,112.5,NULL,NULL,'PKRAGENT20'),
  ('Foresters','Your Term Medical 15/20/25/30 Year',NULL,NULL,60,NULL,NULL,'PKRAGENT10'),
  ('Foresters','Your Term Medical 15/20/25/30 Year',NULL,NULL,56,NULL,NULL,'PKRAGENT9'),
  ('Foresters','Your Term Medical 15/20/25/30 Year',NULL,NULL,52.5,NULL,NULL,'PKRAGENT7'),
  ('Foresters','Your Term Medical 15/20/25/30 Year',NULL,NULL,49,NULL,NULL,'PKRAGENT5'),
  ('Foresters','Your Term Medical 15/20/25/30 Year',NULL,NULL,45,NULL,NULL,'PKRAGENT3'),
  ('Foresters','Your Term Medical 15/20/25/30 Year',NULL,NULL,41,NULL,NULL,'PKRAGT2A'),
  ('Foresters','Your Term Medical 15/20/25/30 Year',NULL,NULL,37.5,NULL,NULL,'PKRAGT2B'),
  ('Foresters','Your Term Medical 15/20/25/30 Year',NULL,NULL,34,NULL,NULL,'PKRAGT2C'),
  ('Foresters','Your Term Medical 15/20/25/30 Year',NULL,NULL,NULL,NULL,NULL,'PKRAGENT1 (LOA)'),
  ('Foresters','Your Term 10 Year',NULL,NULL,65.5,NULL,NULL,'PKRAGENT20'),
  ('Foresters','Your Term 10 Year',NULL,NULL,35,NULL,NULL,'PKRAGENT10'),
  ('Foresters','Your Term 10 Year',NULL,NULL,33,NULL,NULL,'PKRAGENT9'),
  ('Foresters','Your Term 10 Year',NULL,NULL,30.5,NULL,NULL,'PKRAGENT7'),
  ('Foresters','Your Term 10 Year',NULL,NULL,28.5,NULL,NULL,'PKRAGENT5'),
  ('Foresters','Your Term 10 Year',NULL,NULL,26,NULL,NULL,'PKRAGENT3'),
  ('Foresters','Your Term 10 Year',NULL,NULL,24,NULL,NULL,'PKRAGT2A'),
  ('Foresters','Your Term 10 Year',NULL,NULL,22,NULL,NULL,'PKRAGT2B'),
  ('Foresters','Your Term 10 Year',NULL,NULL,19.5,NULL,NULL,'PKRAGT2C'),
  ('Foresters','Your Term 10 Year',NULL,NULL,NULL,NULL,NULL,'PKRAGENT1 (LOA)'),
  ('Foresters','SMART UL',NULL,NULL,150,NULL,NULL,'PKRAGENT20'),
  ('Foresters','SMART UL',NULL,NULL,80,NULL,NULL,'PKRAGENT10'),
  ('Foresters','SMART UL',NULL,NULL,75,NULL,NULL,'PKRAGENT9'),
  ('Foresters','SMART UL',NULL,NULL,70,NULL,NULL,'PKRAGENT7'),
  ('Foresters','SMART UL',NULL,NULL,65,NULL,NULL,'PKRAGENT5'),
  ('Foresters','SMART UL',NULL,NULL,60,NULL,NULL,'PKRAGENT3'),
  ('Foresters','SMART UL',NULL,NULL,55,NULL,NULL,'PKRAGT2A'),
  ('Foresters','SMART UL',NULL,NULL,50,NULL,NULL,'PKRAGT2B'),
  ('Foresters','SMART UL',NULL,NULL,45,NULL,NULL,'PKRAGT2C'),
  ('Foresters','SMART UL',NULL,NULL,NULL,NULL,NULL,'PKRAGENT1 (LOA)'),
  ('Foresters','Advantage Plus SI WL Pay 100',NULL,NULL,140.5,NULL,NULL,'PKRAGENT20'),
  ('Foresters','Advantage Plus SI WL Pay 100',NULL,NULL,75,NULL,NULL,'PKRAGENT10'),
  ('Foresters','Advantage Plus SI WL Pay 100',NULL,NULL,70.5,NULL,NULL,'PKRAGENT9'),
  ('Foresters','Advantage Plus SI WL Pay 100',NULL,NULL,65.5,NULL,NULL,'PKRAGENT7'),
  ('Foresters','Advantage Plus SI WL Pay 100',NULL,NULL,61,NULL,NULL,'PKRAGENT5'),
  ('Foresters','Advantage Plus SI WL Pay 100',NULL,NULL,56,NULL,NULL,'PKRAGENT3'),
  ('Foresters','Advantage Plus SI WL Pay 100',NULL,NULL,51.5,NULL,NULL,'PKRAGT2A'),
  ('Foresters','Advantage Plus SI WL Pay 100',NULL,NULL,47,NULL,NULL,'PKRAGT2B'),
  ('Foresters','Advantage Plus SI WL Pay 100',NULL,NULL,42,NULL,NULL,'PKRAGT2C'),
  ('Foresters','Advantage Plus SI WL Pay 100',NULL,NULL,NULL,NULL,NULL,'PKRAGENT1 (LOA)'),
  ('Foresters','Advantage Plus FU WL Pay 100',NULL,NULL,140.5,NULL,NULL,'PKRAGENT20'),
  ('Foresters','Advantage Plus FU WL Pay 100',NULL,NULL,75,NULL,NULL,'PKRAGENT10'),
  ('Foresters','Advantage Plus FU WL Pay 100',NULL,NULL,70.5,NULL,NULL,'PKRAGENT9'),
  ('Foresters','Advantage Plus FU WL Pay 100',NULL,NULL,65.5,NULL,NULL,'PKRAGENT7'),
  ('Foresters','Advantage Plus FU WL Pay 100',NULL,NULL,61,NULL,NULL,'PKRAGENT5'),
  ('Foresters','Advantage Plus FU WL Pay 100',NULL,NULL,56,NULL,NULL,'PKRAGENT3'),
  ('Foresters','Advantage Plus FU WL Pay 100',NULL,NULL,51.5,NULL,NULL,'PKRAGT2A'),
  ('Foresters','Advantage Plus FU WL Pay 100',NULL,NULL,47,NULL,NULL,'PKRAGT2B'),
  ('Foresters','Advantage Plus FU WL Pay 100',NULL,NULL,42,NULL,NULL,'PKRAGT2C'),
  ('Foresters','Advantage Plus FU WL Pay 100',NULL,NULL,NULL,NULL,NULL,'PKRAGENT1 (LOA)'),
  ('Foresters','Prepared Accidental Death FYC',NULL,NULL,169,NULL,NULL,'PKRAGENT20'),
  ('Foresters','Prepared Accidental Death FYC',NULL,NULL,90,NULL,NULL,'PKRAGENT10'),
  ('Foresters','Prepared Accidental Death FYC',NULL,NULL,84.5,NULL,NULL,'PKRAGENT9'),
  ('Foresters','Prepared Accidental Death FYC',NULL,NULL,79,NULL,NULL,'PKRAGENT7'),
  ('Foresters','Prepared Accidental Death FYC',NULL,NULL,73,NULL,NULL,'PKRAGENT5'),
  ('Foresters','Prepared Accidental Death FYC',NULL,NULL,67.5,NULL,NULL,'PKRAGENT3'),
  ('Foresters','Prepared Accidental Death FYC',NULL,NULL,62,NULL,NULL,'PKRAGT2A'),
  ('Foresters','Prepared Accidental Death FYC',NULL,NULL,56,NULL,NULL,'PKRAGT2B'),
  ('Foresters','Prepared Accidental Death FYC',NULL,NULL,50.5,NULL,NULL,'PKRAGT2C'),
  ('Foresters','Prepared Accidental Death FYC',NULL,NULL,NULL,NULL,NULL,'PKRAGENT1 (LOA)'),
  ('Prudential','Level Term',NULL,NULL,150,NULL,NULL,'150'),
  ('Prudential','Level Term',NULL,NULL,80,NULL,NULL,'80'),
  ('Prudential','Level Term',NULL,NULL,75,NULL,NULL,'75'),
  ('Prudential','Level Term',NULL,NULL,70,NULL,NULL,'70'),
  ('Prudential','Level Term',NULL,NULL,65,NULL,NULL,'65'),
  ('Prudential','Level Term',NULL,NULL,60,NULL,NULL,'60'),
  ('Prudential','Level Term',NULL,NULL,55,NULL,NULL,'55'),
  ('Prudential','Level Term',NULL,NULL,50,NULL,NULL,'50'),
  ('Prudential','Level Term',NULL,NULL,45,NULL,NULL,'45'),
  ('Prudential','Level Term',NULL,NULL,40,NULL,NULL,'40'),
  ('Prudential','Level Term',NULL,NULL,35,NULL,NULL,'35'),
  ('Prudential','Level Term',NULL,NULL,30,NULL,NULL,'30'),
  ('Prudential','Level Term',NULL,NULL,25,NULL,NULL,'25'),
  ('Prudential','MP Term',NULL,NULL,150,NULL,NULL,'150'),
  ('Prudential','MP Term',NULL,NULL,80,NULL,NULL,'80'),
  ('Prudential','MP Term',NULL,NULL,75,NULL,NULL,'75'),
  ('Prudential','MP Term',NULL,NULL,70,NULL,NULL,'70'),
  ('Prudential','MP Term',NULL,NULL,65,NULL,NULL,'65'),
  ('Prudential','MP Term',NULL,NULL,60,NULL,NULL,'60'),
  ('Prudential','MP Term',NULL,NULL,55,NULL,NULL,'55'),
  ('Prudential','MP Term',NULL,NULL,50,NULL,NULL,'50'),
  ('Prudential','MP Term',NULL,NULL,45,NULL,NULL,'45'),
  ('Prudential','MP Term',NULL,NULL,40,NULL,NULL,'40'),
  ('Prudential','MP Term',NULL,NULL,35,NULL,NULL,'35'),
  ('Prudential','MP Term',NULL,NULL,30,NULL,NULL,'30'),
  ('Prudential','MP Term',NULL,NULL,25,NULL,NULL,'25'),
  ('Baltimore Life','iProvide',NULL,NULL,150,NULL,NULL,'150'),
  ('Baltimore Life','iProvide',NULL,NULL,80,NULL,NULL,'80'),
  ('Baltimore Life','iProvide',NULL,NULL,75,NULL,NULL,'75'),
  ('Baltimore Life','iProvide',NULL,NULL,70,NULL,NULL,'70'),
  ('Baltimore Life','iProvide',NULL,NULL,65,NULL,NULL,'65'),
  ('Baltimore Life','iProvide',NULL,NULL,60,NULL,NULL,'60'),
  ('Baltimore Life','iProvide',NULL,NULL,55,NULL,NULL,'55'),
  ('Baltimore Life','iProvide',NULL,NULL,50,NULL,NULL,'50'),
  ('Baltimore Life','iProvide',NULL,NULL,45,NULL,NULL,'45'),
  ('Baltimore Life','iProvide',NULL,NULL,40,NULL,NULL,'40'),
  ('Baltimore Life','A-Priority',NULL,NULL,122,NULL,NULL,'150'),
  ('Baltimore Life','A-Priority',NULL,NULL,65,NULL,NULL,'80'),
  ('Baltimore Life','A-Priority',NULL,NULL,61,NULL,NULL,'75'),
  ('Baltimore Life','A-Priority',NULL,NULL,57,NULL,NULL,'70'),
  ('Baltimore Life','A-Priority',NULL,NULL,53,NULL,NULL,'65'),
  ('Baltimore Life','A-Priority',NULL,NULL,49,NULL,NULL,'60'),
  ('Baltimore Life','A-Priority',NULL,NULL,44.5,NULL,NULL,'55'),
  ('Baltimore Life','A-Priority',NULL,NULL,40.5,NULL,NULL,'50'),
  ('Baltimore Life','A-Priority',NULL,NULL,36.5,NULL,NULL,'45'),
  ('Baltimore Life','A-Priority',NULL,NULL,32.5,NULL,NULL,'40'),
  ('Newbridge','Level Death Benefit',0,79,150,NULL,NULL,'23'),
  ('Newbridge','Level Death Benefit',0,79,75,NULL,NULL,'8'),
  ('Newbridge','Level Death Benefit',0,79,70,NULL,NULL,'7'),
  ('Newbridge','Level Death Benefit',0,79,65,NULL,NULL,'6'),
  ('Newbridge','Level Death Benefit',0,79,60,NULL,NULL,'5'),
  ('Newbridge','Level Death Benefit',0,79,55,NULL,NULL,'4'),
  ('Newbridge','Level Death Benefit',0,79,50,NULL,NULL,'3'),
  ('Newbridge','Level Death Benefit',0,79,45,NULL,NULL,'2'),
  ('Newbridge','Level Death Benefit',0,79,40,NULL,NULL,'1'),
  ('Newbridge','Level Death Benefit',80,85,80,NULL,NULL,'23'),
  ('Newbridge','Level Death Benefit',80,85,40,NULL,NULL,'8'),
  ('Newbridge','Level Death Benefit',80,85,37.5,NULL,NULL,'7'),
  ('Newbridge','Level Death Benefit',80,85,34.5,NULL,NULL,'6'),
  ('Newbridge','Level Death Benefit',80,85,32,NULL,NULL,'5'),
  ('Newbridge','Level Death Benefit',80,85,29.5,NULL,NULL,'4'),
  ('Newbridge','Level Death Benefit',80,85,26.5,NULL,NULL,'3'),
  ('Newbridge','Level Death Benefit',80,85,24,NULL,NULL,'2'),
  ('Newbridge','Level Death Benefit',80,85,21.5,NULL,NULL,'1'),
  ('Newbridge','Modified Death Benefit',0,79,130,NULL,NULL,'23'),
  ('Newbridge','Modified Death Benefit',0,79,65,NULL,NULL,'8'),
  ('Newbridge','Modified Death Benefit',0,79,60.5,NULL,NULL,'7'),
  ('Newbridge','Modified Death Benefit',0,79,56.5,NULL,NULL,'6'),
  ('Newbridge','Modified Death Benefit',0,79,52,NULL,NULL,'5'),
  ('Newbridge','Modified Death Benefit',0,79,47.5,NULL,NULL,'4'),
  ('Newbridge','Modified Death Benefit',0,79,43.5,NULL,NULL,'3'),
  ('Newbridge','Modified Death Benefit',0,79,39,NULL,NULL,'2'),
  ('Newbridge','Modified Death Benefit',0,79,34.5,NULL,NULL,'1'),
  ('Newbridge','Modified Death Benefit',80,85,90,NULL,NULL,'23'),
  ('Newbridge','Modified Death Benefit',80,85,45,NULL,NULL,'8'),
  ('Newbridge','Modified Death Benefit',80,85,42,NULL,NULL,'7'),
  ('Newbridge','Modified Death Benefit',80,85,39,NULL,NULL,'6'),
  ('Newbridge','Modified Death Benefit',80,85,36,NULL,NULL,'5'),
  ('Newbridge','Modified Death Benefit',80,85,33,NULL,NULL,'4'),
  ('Newbridge','Modified Death Benefit',80,85,30,NULL,NULL,'3'),
  ('Newbridge','Modified Death Benefit',80,85,27,NULL,NULL,'2'),
  ('Newbridge','Modified Death Benefit',80,85,24,NULL,NULL,'1'),
  ('Royal Neighbors','Simplified Issue WL',50,75,150,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Simplified Issue WL',50,75,75,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Simplified Issue WL',50,75,70,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Simplified Issue WL',76,80,120,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Simplified Issue WL',76,80,60,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Simplified Issue WL',76,80,56,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Simplified Issue WL',81,85,70,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Simplified Issue WL',81,85,35,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Simplified Issue WL',81,85,32.5,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Graded Death Benefit',50,75,100,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Graded Death Benefit',50,75,50,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Graded Death Benefit',50,75,46.5,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Graded Death Benefit',76,80,80,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Graded Death Benefit',76,80,40,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Graded Death Benefit',76,80,37.5,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Graded Death Benefit',81,85,60,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Graded Death Benefit',81,85,30,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Graded Death Benefit',81,85,28,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Guaranteed Issue WL Band 1',NULL,NULL,22,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Guaranteed Issue WL Band 1',NULL,NULL,11,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Guaranteed Issue WL Band 1',NULL,NULL,10.5,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Guaranteed Issue WL Band 2',NULL,NULL,17,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Guaranteed Issue WL Band 2',NULL,NULL,8.5,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Guaranteed Issue WL Band 2',NULL,NULL,8,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Single Premium WL',NULL,NULL,14,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Single Premium WL',NULL,NULL,7,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Single Premium WL',NULL,NULL,6.5,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Jet WL Band 1',NULL,NULL,100,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Jet WL Band 1',NULL,NULL,50,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Jet WL Band 1',NULL,NULL,46.5,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Jet WL Band 2',NULL,NULL,150,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Jet WL Band 2',NULL,NULL,75,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Jet WL Band 2',NULL,NULL,70,NULL,NULL,'55-SA3-E0033'),
  ('Royal Neighbors','Jet Youth Whole Life',NULL,NULL,100,NULL,NULL,'75-SA1'),
  ('Royal Neighbors','Jet Youth Whole Life',NULL,NULL,50,NULL,NULL,'60-SA2-E0032'),
  ('Royal Neighbors','Jet Youth Whole Life',NULL,NULL,46.5,NULL,NULL,'55-SA3-E0033')
)
INSERT INTO public.commission_grids
  (carrier_id, product_name, age_group_min, age_group_max, year_1_pct, years_2_5_pct, years_6_plus_pct, level_name)
SELECT c.id, d.product_name, d.age_min, d.age_max, d.y1, d.y25, d.y6, d.lvl
FROM grid_data d
JOIN carriers_map c ON c.name = d.carrier_name;
